### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by pwFoo** [LeadDyno/intercooler-js#104]
Would it possible to add websocket (client side) support to intercooler?
Could be interesting...

**Comment by pchaganti** [comment]
👍

**Comment by carsongross** [comment]
Yeah, I've been thinking about this.  I can see it being a good replacement for ic-poll, for example.

What sort of API do you think would be appropriate for it?

**Comment by pwFoo** [comment]
ic-poll shouldn't be replaced and used as fallback / alternative. Ajax polling is just simple and witthout server side dependencies.

That would be the problem with websockets... 
I tested [PHP-Websockets](https://github.com/ghedipunk/PHP-Websockets) because it was simple to use, but it's php only if you try to be independent... 
The server side api shouldn't be to complex.

**Comment by carsongross** [comment]
Cool, I’ll think about the API this week.

Cheers,
Carson

On July 25, 2016 at 12:54:40 AM, pwFoo (notifications@github.com) wrote:

ic-poll shouldn't be replaced and used as fallback / alternative. Ajax polling is just simple and witthout server side dependencies.

That would be the problem with websockets...
I tested PHP-Websockets because it was simple to use, but it's php only if you try to be independent...
The server side api shouldn't be to complex.

**Comment by pwFoo** [comment]
Great :)
But if it will be to complex you shouldn't add it (to core)...
I prefer intercooler because its awesome simple to use ;)

**Comment by carsongross** [comment]
:)

I don’t think it will be too complex, but I agree with the sentiment!

Cheers,
Carson

On July 25, 2016 at 11:48:22 AM, pwFoo (notifications@github.com) wrote:

Great :)
But if it will be to complex you shouldn't add it (to core)...
I prefer intercooler because its awesome simple to use ;)

**Comment by OvermindDL1** [comment]
Also interested in being able to replace the calls it uses.  I have a framework for JS on my server that can push GET/POST/DELETE/Etc... calls over a persistent websocket connection to that server, which significantly reduces the server workload (re-verifying tokens and such) and significantly reduces latency where it can send events to the client (thus no need for 'poll') and it falls back to long-polling on systems without websocket.  I would substantially love being able to replace intercoolerjs's calls through jquery to use this library instead.

**Comment by Ahnfelt** [comment]
Server sent events may be a better first target, since it requires less of the server. It could have this API (endpoint /sse, event tick):

  <div ic-src="/seconds" ic-trigger-event="/sse#tick">You have been on this page for 0 seconds...</div>

**Comment by Ahnfelt** [comment]
I forgot to quote the code in the above comment:

```html
<div ic-src="/seconds" ic-trigger-event="/sse#tick">You have been on this page for 0 seconds...</div>
```

**Comment by Ahnfelt** [comment]
Sinc the endpoint is a URL, and event is a bit generic, a better name may be ic-trigger-src.

**Comment by Ahnfelt** [comment]
I have moved my comments about server sent events to a new issue, since they were starting to derail this issue.

**Comment by carsongross** [comment]
I think Server Sent Events is more consistent with the intercooler approach.  I'm going to leave this open as a potential future feature, but I'd like to see how SSE's work out first.

**Comment by carsongross** [comment]
I'm going to close this out, with SSE support as the answer for this sort of thing in intercooler.

**Comment by aolko** [comment]
well, sse is mostly supported by the browsers
![](http://i.imgur.com/1ByWUOn.png)

**Comment by bmjjr** [comment]
Spent a lot of time implementing SSE with intercooler.  But now find, SSE doesn't work with cloudflare, but they support websockets. It's always something.

**Comment by chg20** [comment]
:/  Sorry to hear that.  Websockets are a complicated API as far as intercooler semantics go.  Do you have any thoughts on what it would look like?
