### ISSUE TITLE
ic-poll if updated?

### ISSUE THREAD

**Issue by pwFoo** [LeadDyno/intercooler-js#105]
How does ic-poll works? I think it will poll and update the content each time it is called? Or is it possible to verify if the content is updated? The poll request could be some html source code to poll each time again and again...

**Comment by carsongross** [comment]
Yeah, it will replace the content each time. Note that if you sent empty content from the server, intercooler treats it as a no-op and won't swap anything. 

I will often encode the last seen element as a  variable that I send up to the server to know if I need to update a polled UI. 

Cheers,
Carson

**Comment by pwFoo** [comment]
Thanks! Good to know and should work for me too :)
