### ISSUE TITLE
Async load page specific styles and scripts?

### ISSUE THREAD

**Issue by pwFoo** [LeadDyno/intercooler-js#106]
I play with intercooler and async page load. Works fine with simple commands / element attributes! :)
Ajax calls work fine. I haven't tested dependencies, but that sounds great to!

But how could I async load page specific stylesheets and scripts? Is there a intercoolerjs / simple way to do it?

For example first page need a accordion with additional styles, but second page is a gallery with a slider.

During search a solution a found [jQuery getScript](https://api.jquery.com/jquery.getscript/) and [loadCss](https://github.com/filamentgroup/loadCSS), but maybe there is a better way. So maybe you have suggestions how I could implement this feature a better way?

**Comment by carsongross** [comment]
You can include <script> and <style> tags in your returned content if you'd like.  I typically try to avoid this and include everything in a global CSS and javascript file that is loaded once when the app is first loaded up.

Also, note that there is an Intercooler.ready( function(rootElement) { ... } } function available to mimic the jQuery read() function, although you need to base everything off the root element passed in to ensure you don't wire in event handlers more than once.

**Comment by pwFoo** [comment]
include should help me with another problem, thanks! :)

To reduce the ajax calls and server side logic I would transport css / js information "inline" inside the html response. Any hint how to handle it?

I transport css / js files and css / js code json encoded and need to
1) get the information from the response.
2) remove it from html response after extracted at client side with javascript.

At the moment I added a hidden div with the json css / js output / information.

**Comment by pwFoo** [comment]
I have found a solution :)
`Intercooler.ready(function (elt) {...})` to handle the injected response. `remove()` the transfer DIV from DOM.
