### ISSUE TITLE
Documentation / examples how to use Intercooler Response Headers?

### ISSUE THREAD

**Issue by pwFoo** [LeadDyno/intercooler-js#109]
I read the documentation about [Intercooler Response Headers](http://intercoolerjs.org/docs.html#responses). Are examples available (for example) how to use X-IC-Open, X-IC-Script, ...?

**Comment by carsongross** [comment]
No examples, but they work pretty intuitively I hope… :)

Cheers,
Carson

On August 16, 2016 at 1:29:30 PM, pwFoo (notifications@github.com) wrote:

I read the documentation about Intercooler Response Headers. Are examples available (for example) how to use X-IC-Open, X-IC-Script, ...?

**Comment by pwFoo** [comment]
I played around and got it. Haven't worked with response header values before that way ;)

php code to set response header:
```
header('x-ic-redirect: http://www.google.de');
header('X-IC-Script: alert("TEST123")');
```
Works fine!

**Comment by carsongross** [comment]
Perfect.

**Comment by pwFoo** [comment]
Sorry for post to a closed topic...

But could you provide a x-ic-trigger example how to use / handle it?
Server (php) side should look like that?
```
$data = array('event' => array('key1' => 'value1', 'key2' => 'value2'));
$json = json_encode($data);
header("x-ic-trigger: $json");
```

How handle it at client (js) side? 
> beforeHeaders.ic(evt, elt, xhr)	Triggered before intercooler headers are processed.
> afterHeaders.ic(evt, elt, xhr)		Triggered after intercooler headers are processed.

Maybe you could add a example for that?

**Comment by carsongross** [comment]
Using jQuery, you would write something like this:

$('body').on('event', function(event, arg) {   
  console.log( arg['key1'] )
} );

I would pick a more descriptive event name, in real life... :)

**Comment by pwFoo** [comment]
Great, thanks! I'm amazed about IntercoolerJS potential :)

So which is the best way to send json data (for example array of stylesheets and scripts to be loaded async)? 
* x-ic-script
* x-ic-trigger
* ???

I try to separate the json information from the intercooler html response.
The json could be a multidimensional array to be handled on client side.

**Comment by carsongross** [comment]
I would probably use a custom event like ‘loadCSS’ and trigger it via the X-IC-Trigger header and passing the CSS to be loaded as an array

Note that you can trigger more than one event by using a JSON object:

{ “event1” : …,
  “event2” : …. }

Cheers,
Carson

On August 17, 2016 at 1:23:53 AM, pwFoo (notifications@github.com) wrote:

Great, thanks! I'm amazed about IntercoolerJS potential :)

So which is the best way to send json data (for example array of stylesheets and scripts to be loaded async)?

x-ic-script
x-ic-trigger
???
I try to separate the json information from the intercooler html response.
The json could be a multidimensional array to be handled on client side.

**Comment by pwFoo** [comment]
Good to know I can trigger more than one event! 

I have two methods to load js files and css files. I also handle inline css / js with other methods. I just rewrite it to event - trigger :)

Continue your excellent work! Thanks for assistance and sharing intercooler!!!

**Comment by carsongross** [comment]
:)

Glad you are finding it useful!

Cheers,
Carson

On August 17, 2016 at 9:52:14 AM, pwFoo (notifications@github.com) wrote:

Good to know I can trigger more than one event!

I have two methods to load js files and css files. I also handle inline css / js with other methods. I just rewrite it to event - trigger :)

Continue your excellent work! Thanks for assistance and sharing intercooler!!!
