### ISSUE TITLE
write jQuery dependency at the top of the readme

### ISSUE THREAD

**Issue by englishextra** [LeadDyno/intercooler-js#111]
not just somewhere close to the bottom.

Why?

Because devs waste time trying to understand what does the library do, and then all of a sudden realise that jQuery is required.

**Comment by carsongross** [comment]
https://github.com/LeadDyno/intercooler-js/commit/84b70602918e7f575d99796900a56ff5c6171eb3

**Comment by englishextra** [comment]
Thanks a lot!
