### ISSUE TITLE
intercooler tag don't work in the page loaded by ajax

### ISSUE THREAD

**Issue by supercreator** [LeadDyno/intercooler-js#112]
My web have automaticlly load more page and i try to use ic tag to implement "view more",it load data from other page into tag, it work in the first page that not load by ajax yet but in the seconde page, any ic tag don't response. Does the ic support something like this? I want to use it. its not complex, Please help me

Thank you

**Comment by carsongross** [comment]
Hi There,

Is the HTML loaded by intercooler, or by some other mechanism?  Are there any javascript errors in the console?

If it is just HTML loaded by intercooler, new intercooler attributes will be processed and hooked up.  If the HTML is coming from somewhere else, you can use Intercooler.processNodes(elt) to process the HTML.

Cheers,
Carson

On August 28, 2016 at 5:37:25 AM, supercreator (notifications@github.com) wrote:

My web have automaticlly load more page and i try to use ic tag to implement "view more",it load data from other page into tag, it work in the first page that not load by ajax yet but in the seconde page, any ic tag don't response. Does the ic support something like this? I want to use it. its not complex, Please help me

Thank you

**Comment by supercreator** [comment]
Success! It's grate, thank you very much Carson Gross, I use code like this

$.ajax({
         url: "loadnewpage.asp", 
         dataType: "html",
         type: 'POST', 
		 data: {pageno: pagenumber,pagecode: pagecode<? if ($senddata."x"<>"x"){?>,senddata:  <?=$senddata?><? } ?>}, 
         success: function(data){if(data.trim().length>2500) {$("#newpage").append(data);loadenable=true;loadpage=loadpage+1;var elt = document.getElementById("newpage");Intercooler.processNodes(elt);} else {endpage=true;}}
		 }).fail(function (xhr,msg,problem) {loadenable=true;});
}


1. However, I try to use ic-push-url="true", it's work only in the same page, when I click to open the new page and press back button, my old pages that are loaded more by Ajax lost, it show only the content in the ic-target element.

2. I think the display command of intercooler is very helpful. It will be better if there are more commands for inputting. Is there the command or an example that can create the drag drop element for uploading file? If user drag image file into the element it will show these images and prepare elements for uploading, In the same drag&drop element if user drag YouTube video or Image from Flickr, it will return YouTube ID or image url elements for posting, support multi-files selecting. Something like these. 

Thank you Carson Gross

**Comment by carsongross** [comment]
Would it be possible to do the next page link via intercooler, rather than using jQuery:

```html
  <a ic-post-to="/loadnewpage.asp?page=2&pagecode=whatever"  
       ic-push-url="true">
     Next Page
  </a>
```

History is heavily tied into snapshotting the current page HTML so it will work best if you are using intercooler for the requests.  Also, I highly recommend you put the `ic-history-elt='true'` on an element that is very stable (e.g. the main body tag) so that the snapshot can be restored more consistently.

**Comment by supercreator** [comment]
I try as you said, it work only when I press new page, page is loaded, then I press back to button in browser and forward to. All contents are recorded correctly, the new page don't lose but when I click into link and go to other page, then press back to, only the new page is shown while the old main content lost.
