### ISSUE TITLE
npm package issue, missing main in package.json

### ISSUE THREAD

**Issue by OvermindDL1** [LeadDyno/intercooler-js#114]
Currently Intercooler is in npm (seems it was last uploaded just today at 1.0.0, nice), however it is not defining a main file for import that defines the main Intercooler CommonJS interface, in addition to the interface is not following CommonJS as far as I can see, making it difficult to import into a module system such as how jquery does it at https://github.com/jquery/jquery/blob/master/package.json#L6 for example, thus making it difficult to combine with jquery via babel into a single large distribution.

**Comment by carsongross** [comment]
Mmm.  How do I fix that? :)

**Comment by OvermindDL1** [comment]
Two things, first need to specify the 'main' file like how jquery does, that will become the default import statement unless otherwise specified.  :-)

The second, two main ways, one uses a transpiler (babel) and the other does not, jquery uses a transpiler, but honestly that is overkill.  If you want to cover all cases that will work for everyone in all ways the easiest thing to do a few things, then (ignoring a few standardeze things like noConflict, which jquery uses, but this library really does not as I doubt no other package will be named 'Intercooler' too ;-) ):

Right now you already have your code wrapped in a private function, which is good, however it currently has `var Intercooler = Intercooler || (function() {` at the top, which is forcing a variable local to the script context, which will be global if `<script ...`'d in, however that style is often disallowed in a lot of contexts (such as here) for security and performance reasons and all such (single entrance point and all that), however in a module system like many npm-using transpilers it puts it in a module, so right now Intercooler gets loaded in, however it is not accessible at all, so the header instead of being `var Intercooler = Intercooler || (function() {` should just be:
```javascript
(function() {
'use strict';
```
Then all the code that is currently inside the module is here up to but not including the return the statement.  At the end replace everything starting at the return statement to the end to be something like:
```javascript
  var Intercooler = {
    refresh: refresh,
    history: _history,
    triggerRequest: fireICRequest,
    processNodes: processNodes,
    closestAttrValue: closestAttrValue,
    verbFor: verbFor,
    isDependent: isDependent,
    getTarget: getTarget,
    processHeaders: processHeaders,
    setIsDependentFunction: function(func) {
      _isDependentFunction = func;
    },
    ready: function(readyHandler) {
      _readyHandlers.push(readyHandler);
    },
    debug: function() {
      var debuggerUrl = closestAttrValue('body', 'ic-debugger-url') ||
      "https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-debugger.js";
      $.getScript(debuggerUrl)
      .fail(function(jqxhr, settings, exception) {
        log($('body'), formatError(exception), "ERROR");
      });
    },
    _internal: {
      init: init,
      replaceOrAddMethod: replaceOrAddMethod
    }
  }

  // AMD/CommonJS/Vanilla support follows

  if (typeof define === "function" && define['amd'])
  {
    define([], function() { return Intercooler; });
    return;
  }

  if (typeof module === "object")
  {
    module['exports'] = Intercooler;
    return;
  }

  var globalIntercooler = this['Intercooler'];
  if (typeof globalIntercooler === "undefined")
  {
    this['Intercooler'] = Intercooler;
    return;
  }

}).call(this);
```

If I have that right that should support any style, 'this' is the global context if `<script ...`'d in, it will be a module context if imported into a given module thus allowing for 'define' or 'module' to be accessed if they exist, etc...  In short, if I have that written correctly (pretty sure I do, it is mostly copy-pasted from the main styles), then it should work everywhere in every system.

Currently Intercooler does not have '$' defined if imported into a module, however if that module imports jquery into $ then imports Intercooler then it should work via the `this` as well.  So with an ES6 transpiler (babel) then including Intercooler is as simple as adding this to the package.json's file dependency section:
```json
    "intercooler": ">=1.0.0",
```
Then just import it into the application javascript on whatever pages will be used by doing:
```javascript
import $ from "jquery"
import Intercooler from "intercooler"
```

:-)

**Comment by OvermindDL1** [comment]
Do note, I am uncertain if `$` will be auto-imported properly, I 'think' so, but I'm used to libraries taking a constructor that takes jquery that they then use so there is no naming issue, which might be better to do anyway as not all sites can use `$` for jQuery (although mine can).

**Comment by OvermindDL1** [comment]
Yeah and some quick tests of changing intercooler locally does get it recognized by the module system properly, but then intercooler dies due to '$' not being defined, it might need to be passed in...

**Comment by OvermindDL1** [comment]
A work-around for users for now, same work-around as bootstrap needs for example, just add this after the import for jquery and before the import for Intercooler:
```javascript
window.$ = $;
```

It works, its a known thing since bootstrap does the same, but passing it in or dynamically testing for the module system at the start (like it is done at the end) and getting jquery from the module system would be better.  I could probably come up with code for that too if you want?  :-)

**Comment by OvermindDL1** [comment]
Sorry for the message count, also need to change the import for Intercooler to this as well so it gets the local scope instead of module scope.  :-)
```javascript
var Intercooler = require("intercooler"); // Or let instead of var if ES6
```

**Comment by carsongross** [comment]
Holy Moly.  I don’t want to change a bunch of code to make node happy, but I also want it to work reasonably well.  Is there a small set of “good enough” changes you can suggest?  If so, can you implement them as a pull request?  

Yes, I’m putting you to work on this.  :)

Cheers,
Carson

On September 12, 2016 at 3:00:09 PM, OvermindDL1 (notifications@github.com) wrote:

Yeah and some quick tests of changing intercooler locally does get it recognized by the module system properly, but then intercooler dies due to '$' not being defined, it might need to be passed in...

**Comment by OvermindDL1** [comment]
> Holy Moly.  I don’t want to change a bunch of code to make node happy, but I also want it to work reasonably well.  Is there a small set of “good enough” changes you can suggest?  If so, can you implement them as a pull request?  

Lol, it is not node actually, but rather the babel transpiler (which is used with a lot of things, including things that are not node, I'm not using node for example) or other systems such as CommonJS, AMD, and others (there are a lot of javascript module systems, thankfully CommonJS took over and was pulled pretty well entirely into the new Javascript ES6 standard, which is what babel converts, from ES6 to ES5).  Basically the way Intercooler is now is that it can really only be brought in via a `<script ...` tag, which is not always possible, especially via embedded build system (such as what I am using).  :-)

> Yes, I’m putting you to work on this.  :)

Heh, if I get time I will.  A big change that should be done is not using `$` to access jQuery, at all, but rather it should be passed in as an object as detailed on the jQuery [Basic Plugin Creation](https://learn.jquery.com/plugins/basic-plugin-creation/) instruction page where they give the basic example as:
```javascript
(function( $ ) {
  // Code that uses jQuery goes here inside this closure
}( jQuery ));
```
The `$` is not always available even when `<script ...`'ing brought in jQuery, however it is understood that jQuery should always be accessible in the scope where the function is being loaded as per their guidelines.

After that just wrapping it up in something to support modules lets it run everywhere.  CommonJS was created, which is what gives you the 'require' capabilities on the client-side, however Node came up with its own called AMD, which is like CommonJS, similar calls, but it is scoped into a 'module', then ES6 came out a while back that added in tons of features like native classes, proper variable scoping with `let`, a module system, and much much so much more (actually makes javascript half-decent to use), browsers are slowly adding native support, but the babel transpiler takes ES6 (and ES7, yes there is ES7 now, ES6 is pretty old at this point and many, dare I say most modern javascript projects are written in ES6/ES7 due to the immense simplicity in code in gives) and outputs stock vanilla ES5 (that is why you see projects, like jquery) that have a 'src' directory, often with lots of files, that get used with babel via a build system like brunch or so (I think jquery uses node as its build system, very low level, slow, and verbose, but eh...) that compiles any ES6/ES7 code to ES5 then combines all the files into a single optimized file into an output directory (usually 'dist', like in the case of jQuery and others too), and that file is usually also taken and put through js uglifier to shrink it down to make a <name>.min.js version of the file from <name>.js, all part of the build system too.

jQuery works fantastically with these module systems for example, but instead of going through all that work you can fake it just by putting on an appropriate header/footer around your javascript.  :-)

I will try to PR in such a header soon if I get time, though feel free to beat me to it.  :-)

**Comment by OvermindDL1** [comment]
I think I have CommonJS and AMD backwards actually... Point remains, almost everyone uses ES6 modules now, like jquery.  :-)

**Comment by OvermindDL1** [comment]
Ooo, and actually the pattern I showed above is apparently well site, I keep seeing https://github.com/umdjs/umd referred to in various posts, it does indeed look like it details how to do it, including a loader for jquery in any context for plugin usage.  :-)

**Comment by OvermindDL1** [comment]
And it looks like intercooler uses Grunt for its build system (please output what we as users should use to a different directory, like `dist`, instead of just `www/release` with a ton of versions?  :-) ), and Grunt has a plugin to automatically umdize output:  https://www.npmjs.com/package/grunt-umd / https://github.com/bebraw/grunt-umd  :-)

**Comment by OvermindDL1** [comment]
Would you mind if a PR updates the package.json grunt entries as they are *extremely* out of date?

**Comment by OvermindDL1** [comment]
PR sent:  https://github.com/LeadDyno/intercooler-js/pull/117

**Comment by carsongross** [comment]
Pulled in your request, will publish next week as intercooler 1.0.1
