### ISSUE TITLE
Element added event incorrect target

### ISSUE THREAD

**Issue by OvermindDL1** [LeadDyno/intercooler-js#118]
Currently trying to use the "elementAdded.ic" callback to re-materialize elements via mdl.  I have a button that is clicked that changes 'another' element via `ic-target`, however the event that is passed into the callback has the `target` set to the button, not to the targeted element.  Ideally both would be accessible via the event, but I only see `target` and not seeing anything else containing a DOM element.  Should not the target for the "elementAdded.ic" event be the element that is added, not the element that did the request?

**Comment by OvermindDL1** [comment]
Do note, `currentTarget` and `delegateTarget` are both `<body>` so those are not it either.

**Comment by OvermindDL1** [comment]
And a work-around is something like:
```javascript
    let target = evt.target;
    if($(target).attr("ic-target")) target = $($(target).attr("ic-target"))[0];
```

**Comment by carsongross** [comment]
Yeah, we should pass the actual target in to that event as well as the triggering element.  I'll do so.

If I'm understanding correctly, I think you might find Intercooler.ready(function(root) { ... } )  more suitable for this use case.  

That's what it's designed for, anyway: to be similar to the $() function in jQuery, except all your queries are relative to the root element rather than the entire document.

**Comment by OvermindDL1** [comment]
Ah, does `Intercooler.ready(func(elt))` operate only on swapped content every time content is swapped?  That would indeed likely be a better method.  :-)

**Comment by OvermindDL1** [comment]
And `Intercooler.ready` has an issue too, it seems to only be passed the old element, not the new one.  Perhaps 'ready' should be renamed to 'swapped' or so and passed both the old and new elements?  Also it seems to be using jQuery's `replaceWith` call, which does not destroy the old element, thus:
1. The old element still exists.
2. The old element is leaking memory (need to properly destroy it as active javascript handlers attached to it will cause leaking).
3. The line where you have `target.replaceWith(contentToSwap);` and then `fireReadyStuff($(target));`, which calls the `ready` callbacks, it being called with the old element.
4. Thus the fireReadyStuff should be given both the old and new elements, and then the old element should be properly destroyed so javascript event handlers attached to them (like via intercooler or mdl) do not keep it around eating memory.

The jQuery `replaceWith` does return the new collection of in-dom elements, so saving that and passing it to the callbacks would be best.

Hmm, this should be a new issue, making...
