### ISSUE TITLE
Possible to leak memory in DOM Swaps

### ISSUE THREAD

**Issue by OvermindDL1** [LeadDyno/intercooler-js#121]
Continued from https://github.com/LeadDyno/intercooler-js/issues/118.

DOM Swaps seem to be using jQuery's `replaceWith` call, which does not destroy the old element, thus:
1. The old element still exists.
2. The old element is leaking memory (need to properly destroy it as active javascript handlers attached to it will cause leaking).
3. The line where you have `target.replaceWith(contentToSwap);` and then `fireReadyStuff($(target));`, which calls the `ready` callbacks, it being called with the old element.
4. Thus the fireReadyStuff should be given both the old and new elements, and then the old element should be properly destroyed so javascript event handlers attached to them (like via intercooler or mdl) do not keep it around eating memory.

**Comment by OvermindDL1** [comment]
And I profiled the page and indeed my element is being leaked according to chrome, detached from the DOM tree but still referenced by javascript event handlers so not being removed and permanently eating memory until page is reloaded.

**Comment by OvermindDL1** [comment]
I searched around for good information about the best way to delete and handle these, first thing found this *second* post on StackOverflow (not the accepted one, it is wrong) [here](http://stackoverflow.com/questions/8830839/javascript-dom-remove-element) but posted here:
> When you unlink a node using removeChild() or by setting the innerHTML property on the parent, you also need to make sure that there is nothing else referencing it otherwise it won't actually be destroyed and will lead to a memory leak. There are lots of ways in which you could have taken a reference to the node before calling removeChild() and you have to make sure those references that have not gone out of scope are explicitly removed.
> 
> Doug Crockford writes [here](http://javascript.crockford.com/memory/leak.html) that event handlers are known a cause of circular references in IE and suggests removing them explicitly as follows before calling removeChild()
> ```javascript
function purge(d) {
    var a = d.attributes, i, l, n;
    if (a) {
        for (i = a.length - 1; i >= 0; i -= 1) {
            n = a[i].name;
            if (typeof d[n] === 'function') {
                d[n] = null;
            }
        }
    }
    a = d.childNodes;
    if (a) {
        l = a.length;
        for (i = 0; i < l; i += 1) {
            purge(d.childNodes[i]);
        }
    }
}
```
> And even if you take a lot of precautions you can still get memory leaks in IE as described by Jens-Ingo Farley [here](http://com.hemiola.com/2009/11/23/memory-leaks-in-ie8/).
> 
> And finally, don't fall into the trap of thinking that Javascript delete is the answer. It seems to be suggested by many, but won't do the job. [Here](http://perfectionkills.com/understanding-delete/) is a great reference on understanding delete by Kangax.

**In addition**, if any other javascript is holding on to an element directly (like mdl does) then that will also keep it from being purged from memory, hence why we should probably have both a 'removed' and an 'added' callback, so we can remove handlers when the element is removed from the DOM and we can add our handlers when it is added.

**Comment by OvermindDL1** [comment]
And remember that you can use the Chrome Browser Profiler to see what is leaking (a bit noisy when you first start using it but it starts to become clear once you learn it).

**Comment by OvermindDL1** [comment]
And some quick testing by using the combined incorrect `Intercooler.ready(...)` and `$("body").on("elementAdded.ic", ...)` calls gets me both the old and new elements and by calling mdl's `componentHandler.downgradeElements(...)` on the old and `componentHandler.upgradeElements(...)` on the new gets everything working and no memory leaks reported (thus Intercooler is not holding internal events it seems from a cursory test :-) ).

This is a hack, and both of those calls are currently slightly broken in different ways ("elementAdded.ic" is not referencing the target that is changed and `Intercooler.ready` is referencing the old element, not the new), so those should be fixed.  But we definitely need a way to receive both an element being removed and one being added.  I'd propose removing the `Intercooler.ready` callback (or deprecating it at least) and adding an `Intercooler.elementRemoved(oldElementBeforeDomRemoval)` and `Intercooler.elementAdded(newElementAlreadyOnDom)`, and/or an `Intercooler.elementsSwapped(oldElementAfterDomRemoval, newElementAlreadyOnDom)` so us clients do not leak memory by using Intercooler.  :-)

**Comment by OvermindDL1** [comment]
At the least yeah, that is the only place the jQuery `replaceWith` is used, but it will also happen any time an element is removed from the DOM without being properly cleaned up as well, and there are **multiple** calls to `remove()` such as in `prepend`, `append`, `processHeaders` when a "X-IC-Remove" is sent, `handleRemoveAfter`, etc...  In general, if there is every a time that an element is removed from the DOM, replaced on the DOM, or in anyway is disconnected from the DOM we need a way to be able to clean up deleted elements or we will get massive client memory leaks over time until the browser tab (or browser itself, depending on the browser) crash.  :-)

Sure, I'll be at work from 8am-5pm MDT (so I am one hour 'after' you, your 7am is my 8am), and I will be sporadically available during work, work depending, or potentially free afterwords, depending on family.  :-)

I'm most easily reached on Gitter.im, I sometimes frequent the Elixir and Elm Slacks (though not often, Slack's interface is bad bad bad for programmers, Gitter.im is Slack but for programmers, tied to git).  I'm sometimes on IRC on esper.net.  And I can be reached on Google Hangouts (via OvermindDL1).  I can help go through and test code.  :-)

**Comment by OvermindDL1** [comment]
It seems different callbacks are called at different times, but there is nothing that reliably gives me the old element in all cases (pre-swap) and the new element (post-swap) both, such calls would fix the other event handlers.  :-)

How about an `Intercooler.removedElementsPreSwap(function(elems){})` and an `Intercooler.removedElementsPostSwap(function(elems){})` and an `Intercooler.addedElementsPreSwap(function(elems){})` and an `Intercooler.addedElementsPostSwap(function(elems){})`?  That would handle all my cases.  :-)

Or combine them for fewer calls via `Intercooler.elementsPreSwap(function(oldElems, newElems){})` and an `Intercooler.elementsPostSwap(function(oldElems, newElems){})`, with undefined for the argument where one or the other is not valid (or instead of invalid an empty jQuery $() container, although undefined would probably be better even if it requires doing a test in the user code).

**Comment by carsongross** [comment]
:)  

Just sat down at my desk.  I will try to sign up for gitter now...

Cheers,
Carson

On September 16, 2016 at 8:15:04 AM, OvermindDL1 (notifications@github.com) wrote:

It seems different callbacks are called at different times, but there is nothing that reliably gives me the old element in all cases (pre-swap) and the new element (post-swap) both, such calls would fix the other event handlers. :-)

How about an Intercooler.removedElementsPreSwap(function(elems){}) and an Intercooler.removedElementsPostSwap(function(elems){}) and an Intercooler.addedElementsPreSwap(function(elems){}) and an Intercooler.addedElementsPostSwap(function(elems){})? That would handle all my cases. :-)

Or combine them for fewer calls via Intercooler.elementsPreSwap(function(oldElems, newElems){}) and an Intercooler.elementsPostSwap(function(oldElems, newElems){}), with undefined for the argument where one or the other is not valid (or instead of invalid an empty jQuery $() container, although undefined would probably be better even if it requires doing a test in the user code).
