### ISSUE TITLE
problem in send form data with post method on firefox

### ISSUE THREAD

**Issue by nimafam** [LeadDyno/intercooler-js#124]
There is a problem with submitting form in mozila firefox, When I try to submit, page has reloaded and I lost some of my data that `echo`  from controller  and it just happen in firefox and in chrome it works well.

I make `ic-push-url="false"` and it must work but I don't understand why it happens?

**Comment by carsongross** [comment]
You probably don’t want to push the URL with form submission, right?  Or is this a search?

Cheers,
Carson

On September 24, 2016 at 1:12:55 AM, nimafam (notifications@github.com) wrote:

There is a problem with submitting form in mozila firefox, When I try to submit, page has reloaded and I lost some of my data that echo from controller and it just happen in firefox and in chrome it works well.

I make ic-push-url="false" and it must work but I don't understand why it happens?

**Comment by nimafam** [comment]
Thank's for your answer, no I don't want to push URL. 
I have form that contains a 2 field, I should get the data send to the controller and specific function check that field with DB to see if is exist or not, After that I echo some popup (modal) from controller to view.
But in this step when I try echo popup and after echo that the page has reloaded.

I check access log and I found that after firing POST request sometimes fires a GET request and I don't know why?and it  just happens in Mozila  and works fine in chrome.
