### ISSUE TITLE
Server sent events support?

### ISSUE THREAD

**Issue by Ahnfelt** [LeadDyno/intercooler-js#131]
[Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) are great for implementing things like chat. They use the HTTP protocol, are easily polyfilled and don't require much from the server.

I propose the following syntax for triggering on endpoint `/sse`, event `tick`. The event is optional:

``` html
<div ic-get-from="/seconds" ic-trigger-src="/sse#tick">You have been on this page for 0 seconds...</div>
```

It's also possible to transfer HTML directly via Server-sent events, without an additional request. Perhaps add an `ic-event-src` that updates the HTML from the `data:` lines in the event source?

``` html
<div ic-event-src="/sse#tick">You have been on this page for 0 seconds...</div>
```

**Comment by carsongross** [comment]
Done and shipped!

**Comment by Ahnfelt** [comment]
Awesome!
