### ISSUE TITLE
Relative links with ic-get-from

### ISSUE THREAD

**Issue by trans** [LeadDyno/intercooler-js#135]
I gave `ic-get-from` a try, and it works well. One feature it is missing that would be really cool though is if it could keep relative-links relative to the location of the source. As it stands it makes all relative-links relative to the importing "parent" document. I realize in most cases the later is what designers will want, but in some cases it would be useful to have the former. For example, consider a single-page blog "app" that loads posts dynamically. If a post's images are relative to the post file, it won't work.

Intercooler.js looks pretty awesome, btw. Major kudos!

**Comment by carsongross** [comment]
Can you give a brief explanation of how this would work with, say, an image tag?

**Comment by carsongross** [comment]
Closing out, feel free to reopen with a good example.
