### ISSUE TITLE
The conflict with Turbolinks?

### ISSUE THREAD

**Issue by afuno** [LeadDyno/intercooler-js#137]
There are several action (pages) in the Home controller.
On all these pages I use "Lazy Loading A Div": http://intercoolerjs.org/examples/lazyload.html

When I go to a page component is not loaded.
Indicator revolves all the time, and the request is not sent.

If the page to restart, then everything is fine.

How to fix it?

**Comment by carsongross** [comment]
If you are loading up with Turbolinks you will need to invoke
```javascript
Intercooler.processNodes($('body'))
```
after each turbolinks request:

https://github.com/LeadDyno/intercooler-tutorial-app/commit/c361ad370320632d69bec6964afdd57b94a182d5#commitcomment-19747147

**Comment by afuno** [comment]
Yep, thx 👍

**Comment by ckritzinger** [comment]
In case anyone stumbles on this, I had to do the following to get Intercooler and turbolinks to play along nicely:

```
!function (window, document, $, undefined) {

    var ready;
    ready = function () {
        if($(document).data('ic-init')) return;
        console.log("intercooler init" + Math.random())
        Intercooler.processNodes($('body'));
        $(document).data('ic-init', true);
    };

    $(document).on('turbolinks:render', ready);
    $(document).on('turbolinks:click', function(){
        $(document).data('ic-init', null);
    });

}(window, document, jQuery);
```

The reason for the slight messiness is that IC already attaches to the body by default on page load. So adding it to the "turbolinks:load" event means that it would have two event listeners on each element.  Which means everything happens twice happens twice.

Unfortunately, Turbolinks does not have any events that happen exactly once during turbolinks nav events (render is called twice) and it seems Intercooler does not have a mechanism that allows us to check if it has already been initialised.

**Comment by mindreframer** [comment]
The proposed snippet caused some issues for me. 

here is what worked: 


```js
(function(){
  if ($(document).data('ic-init')) return;
  document.addEventListener("turbolinks:render", function(){Intercooler.processNodes($('body'));})
  $(document).data('ic-init', true);
})()
```

maybe that helps somebody.
