### ISSUE TITLE
ic-replace-target leaving outer replaced elements around

### ISSUE THREAD

**Issue by wmwragg** [LeadDyno/intercooler-js#139]
When I add:

```
        <a class="button button--primary" ic-post-to="/click?issue=1" ic-replace-target="true">
            <span>Click Me!</span>
        </a>
```

to my `index.html` and use mockjax with the following:

```
$.mockjax({
    url: /\/click.*/,
    responseTime: config.responseTime,
    response: function (settings) {
        var queryStr = settings.url.substring(settings.url.lastIndexOf('?'));
        var params = utils.parseParams(queryStr);

        var issue = parseInt(params['issue']);

        this.responseText = '\
        <a class="button button--primary" ic-post-to="/click?issue=' + (issue + 1) + '" ic-replace-target="true">\
            <span>You clicked me ' + issue + ' times...</span>\
        <\a>';
    }
});
```

The component does get replaced, but each time I hit the button a new `<a></a>` is created, e.g. after two clicks the HTML looks like:

```
        <a class="button button--primary" ic-post-to="/click?issue=1" ic-replace-target="true">
            <span>Click Me!</span>
        </a>
        <a></a>
        <a></a>
```

and after 4 clicks:

```
        <a class="button button--primary" ic-post-to="/click?issue=1" ic-replace-target="true">
            <span>Click Me!</span>
        </a>
        <a></a>
        <a></a>
        <a></a>
        <a></a>
```

This happens in Safari and Chrome.

I'm using:

jquery (Version 3.1.1)
intercooler (Version 1.0.3)
jquery.mockjax (Version 2.2.1)
MacBook Air running MacOS Sierra (Version 10.12.1)
Safari (Version 10.0.1)
Chrome (Version 54.0.2840.98 (64-bit))

**Comment by carsongross** [comment]
I've reproduced the issue in a unit test and will fix next week, after the holiday.  Very strange: I'm just using jQuery replaceWith!

**Comment by carsongross** [comment]
AHAHAHAHAHAHAHAHAHA!


Finally figured this out!  The sample code ends with a "<\a>" rather than a "</a>", so it is being interpreted as a new tag.

:)
