### ISSUE TITLE
Add ic-poll-limit or similar, exponential backoff

### ISSUE THREAD

**Issue by gabrielbauman** [LeadDyno/intercooler-js#14]
It would be great if there was a declarative way to specify maximum number of allowable polling events. This would make it easy to head off polling events from people who leave browsers open and walk away for days at a time, for instance.

Something like this: 
```
<div ic-poll="5s" ic-poll-limit="200"></div>
```

I am aware that the server can cancel polling by sending an X-IC-CancelPolling header, but if (say) the server is throwing 500 Server Errors or 404 Not Founds that won't work. Having clients continue to hammer your server when it's down is Not Nice ;)

In fact, it would be good to see exponential backoff in the case of server errors. First HTTP 500, poll time doubled, another 500, next poll time doubled again, and after a certain number of 500s polling would be disabled. Maybe a smaller multiple.

**Comment by carsongross** [comment]
Closing, we handle this by only queuing one request at a time and not stacking requests.

**Comment by gabrielbauman** [comment]
So just to be clear, if one request fails, the poll stops?
