### ISSUE TITLE
scrolled-into-view triggers for hidden tabs

### ISSUE THREAD

**Issue by fullergalway** [LeadDyno/intercooler-js#144]
Great library, thanks.

I noticed in my bootstrap 3 application, the "scrolled-into-view" action is firing for an offscreen tab. The action stops firing only when all the "pages" have been loaded, or the user switches to that tab (whichever comes first).

Thanks again,

**Comment by fullergalway** [comment]
Created merge request #145 for this issue.

**Comment by carsongross** [comment]
merged fix into dev, thanks!
