### ISSUE TITLE
Broken jQuery CDN URL

### ISSUE THREAD

**Issue by impressivewebs** [LeadDyno/intercooler-js#146]
[The download page](http://intercoolerjs.org/download.html) uses the following jQuery link:

http://code.jquery.com/jquery-1.10.3.min.js

But that link is broken. I assume it should be:

https://code.jquery.com/jquery-1.10.2.min.js

Because there doesn't seem to be a 1.10.3 release. You can also use:

https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.js

EDIT: Your demo pages seem to use 1.10.2, so I assume it was just a typo.

**Comment by carsongross** [comment]
Thanks!
