### ISSUE TITLE
Intercooler Error : TypeError: c is not a function

### ISSUE THREAD

**Issue by n3storm** [LeadDyno/intercooler-js#152]
Any idea why I get this error in console?

jquery 2.2.4 could be the culprit? At docs always jquery 1.x is mentioned.

Thanks in advance.

**Comment by carsongross** [comment]
can you attach the error?

**Comment by carsongross** [comment]
I mean the stack trace for the error?

**Comment by carsongross** [comment]
Any update?  I'd like to see the stack trace for the element, to understand the issue.  It looks like an internal issue or you are using minified code?

**Comment by carsongross** [comment]
ping

**Comment by carsongross** [comment]
Closing out for lack of response
