### ISSUE TITLE
ic-indicator only selects first element

### ISSUE THREAD

**Issue by jpulec** [LeadDyno/intercooler-js#153]
It seems that although ic-indicator accepts any CSS selector, it only uses the first one it finds. Not sure if this was intentional or not. I ran into a scenario where I had a spinner element that was the sibling element to my swapped in set of data. I was trying to use multiple indicators (using a class CSS selector) in combination with ic-use-transition to try to get my data element to be hidden when the request was in flight and the spinner was being shown. If there's a clearer way to do that, I'd love to know.

**Comment by carsongross** [comment]
Can you give me a rough outline of your HTML?  We should be able to work something out.
