### ISSUE TITLE
data argument to event of 'beforeSend.ic' is not useful

### ISSUE THREAD

**Issue by flaub** [LeadDyno/intercooler-js#154]
The `beforeSend.ic` documentation states:

> Triggered before sending an intercooler AJAX request to the server. The second argument to the event is the data hash, and can be added or removed from to change the values sent to the server.

This wording is a little unclear, there's two ways to interpret it:
1. The 'data hash' is the `data` argument passed to the event callback (which is actually the 3rd argument)
2. The 'data hash' is the `data` property on the `evt` argument.

In either case, I get something that isn't very useful. The `data` argument is the post-encoded string that will go on the wire in the ajax request. The `data` property of the `evt` argument is `undefined`.

I would really like to have access to an object that represents all the fields in a form so that I can arbitrarily manipulate it before it gets encoded and sent to the server (as the documentation alludes to about changing values sent to the server).

**Comment by flaub** [comment]
Example: https://jsfiddle.net/coh62127/2/

**Comment by flaub** [comment]
I see in the code that we either construct a `FormData` or just a string and then manually append fields. An object with key/value pairs could instead be created, the trouble is how to grab the existing fields from a parent form. Currently this is via a call to `closestForm.serialize()`. Perhaps a call to `closestForm.serializeArray()` would achieve what I'm looking for?

**Comment by scottwoodall** [comment]
I came across this today and had the same difficulties with the documentation as @flaub. I was hoping to remove one of the values in the data object before it gets sent to the server but I didn't see a straight forward way like the documentation mentions.

**Comment by carsongross** [comment]
I have put up an example of how to modify intercooler requests client side:

http://intercoolerjs.org/examples/modifying_requests.html
