### ISSUE TITLE
intercooler.js AJAX calls fail (403) when deployed on AWS Lambda via Zappa

### ISSUE THREAD

**Issue by bobcolner** [LeadDyno/intercooler-js#156]
## Context
[Zappa](https://github.com/Miserlou/Zappa) is a python tool for deploying standard web-servers (flask, etc.) as [AWS Lambda](https://aws.amazon.com/lambda/) functions. This is great because Lambda is very cheap, and scaleable, and simple!

For reasons unknown to me,  Intercooler AJAX calls fail (`403`) when deployed on AWS via Zappa. The API routes used for the AJAX calls work when browsed to directly.
 
I've linked to a minimal reproduction of the issue. 

## Expected Behavior
Index.html contains a single `<h1>` tag endouded with a intercooler ajax directive. Clicking on the button should result in API path specified in `ic-get-from` being called and the `<h1>` element being replaced with the response.

`bug_server.py` implements the flask server for the example app.

## Actual Behavior
When run locally the app returns a new random string from the server each time the test button is clicked.

When deployed via Zappa the AJAX calls fails with a `403` forbidden code.
Details: https://raw.githubusercontent.com/bobcolner/zappa-intercoolerjs-issue/master/screenshots/ajax%20bug%20trace.png

## Steps to Reproduce

1. Minimal flask+intercooler.js app: https://github.com/bobcolner/zappa-intercoolerjs-issue
2. To Run locally in a virtual env (ajax 'click me' button should work): `pip install -r requirments.txt && python bug_server.py`
3. Deploy on AWS via `Zappa init` and `Zappa deploy dev`

## Context
Both Zappa and Intercooler.js enable **Low Complexity** development. I'm excited about combining serverless tech like Zappa (low complexity, great economics and scaling) and low-complexity but compelling UX frontend tech -aka Intercooler.js. 

Thanks for your help on this.

## Your Environment

* Zappa version used: latest
* Intercooler version used: latest
* Operating System and Python version: OS X, virtual env, python2.7
* Link to your project (optional): https://github.com/bobcolner/zappa-intercoolerjs-issue

**Comment by bobcolner** [comment]
The issue is due to Zappa modify the root URL (adding a /dev/ or /prod/). Not an intercooler.js issue.

**Comment by carsongross** [comment]
Glad you figured it out!  Hope intercooler is useful.
