### ISSUE TITLE
Respect special headers on error responses

### ISSUE THREAD

**Issue by cortesi** [LeadDyno/intercooler-js#158]
I would like to return a 403-forbidden response and redirect the user to a login page with the X-IC-REDIRECT header. At the moment, any 4xx response results in an "AJAX request ... encountered an error" console log, and I can see from the code that headers aren't processed in the error handler.

**Comment by carsongross** [comment]
Fixed with https://github.com/LeadDyno/intercooler-js/commit/a28d67f975309db5080434d8d5dcff33fcdbac0f
