### ISSUE TITLE
enable client side templates

### ISSUE THREAD

**Issue by unuseless** [LeadDyno/intercooler-js#163]
Would be great if intercooler worked together with client side templating.
https://mmikowski.github.io/no-frameworks/ here Carson Gross made a comment:
"I am going to add support for client side templates soon (maybe tomorrow if I have time...)"

Maybe a bit similar to the mockjax stuff in the examples, i.e. loading data from the server and putting it into something similar to the mockjax things?

**Comment by bobcolner** [comment]
thats a great idea!

**Comment by genez** [comment]
related to client-side templating, I am currently trying to use intercooler with handlebars.js
my first attempt consists of a div (the target container) like this:

`<div id="inbox-container" class="card-block" ic-poll="250ms" ic-poll-repeats="1" ic-src="/contacts"></div>`

where /contacts is a JSON feed. But as I didn't find a way to *modify* the response body after a successful operation, I hijacked the jquery onsuccess event and wrapped up thing with the help of a small function (taken from [this gist](https://gist.github.com/topliceanu/4175125)):

```
alterResponse({
        urlMatch: '/contacts',
        successWrapper: function (options, originalOptions, jqXHR, next) {
            var obj = JSON.parse(jqXHR.responseText);
            var response = inboxTemplate(obj);
            next(response, jqXHR.statusText, jqXHR);
        }
    });
```

It *works*, but it's kinda ugly.

**Comment by carsongross** [comment]
The latest release allows this with the ic-transform-response attribute:

http://intercoolerjs.org/attributes/ic-transform-response.html

**Comment by unuseless** [comment]
Thanks.  Looking forward to try this!
The docs at http://intercoolerjs.org/attributes/ic-transform-response.html
show an example for `ic-append-from`, so maybe this is not the right page?

**Comment by carsongross** [comment]
thanks for pointing that out, I have updated the example page

**Comment by pwFoo** [comment]
Would it possible to add template with `ic-template=URL` to load a template and parse it with  (json) data from another ic ajax call?
I know it would need some template engine / parser...
