### ISSUE TITLE
Include clicked button for GET forms

### ISSUE THREAD

**Issue by jsampson-gw** [LeadDyno/intercooler-js#167]
Currently, the name & value of a clicked button are included along with the submitted form only if it is **not** using GET. I would like to have them included for GET as well.

See discussion here: https://groups.google.com/forum/#!topic/intercooler-js/0pTkp3aheMU

**Comment by carsongross** [comment]
Fixed w/ https://github.com/LeadDyno/intercooler-js/commit/ce5c9bcb71181c6858a3e26adc02b62c721e3994
