### ISSUE TITLE
Use HTTP HEAD to determine if polling should fetch new data or not.

### ISSUE THREAD

**Issue by flexd** [LeadDyno/intercooler-js#17]
A HEAD request returns the Content-Length header, which as you see here can be a good indicator to check if the content has changed:

![sonar_contentlength](https://cloud.githubusercontent.com/assets/2317/3016038/64246dc2-df69-11e3-8786-bc1e4708de9c.png)

For larger requests, a lot of bandwidth can be spared if Intercooler does a HEAD request to check if the data has been updated, instead of doing a full GET request and then comparing the data.

**Comment by carsongross** [comment]
Closing.  I'd like the browser to handle this by interpreting standard HTTP response codes, like 304
