### ISSUE TITLE
Global trigger and ic-target

### ISSUE THREAD

**Issue by rippo** [LeadDyno/intercooler-js#170]
I am having an issue where I have `ic-target` and a global trigger attached to the body does not seem to work together.

My input control

```
<input name="qty"
  ic-target="#popupBasketType-1"
  ic-post-to="/ajax/basket/change"
  ic-trigger-on="change"
  type="number" min="1  max="1 step="1" 
  value="1" />
```

The global event that **does NOT get called** is:-

```
    //Basket changed, checkout page
    $("body").on("ic-trigger-change-basket-item", function (elt, arg) {
        changeUi(arg);
    });
```

My code that returns both HTML and the header

```
        public ActionResult Change(int id, int qty, PopupBasketType popupBasketType)
        {
            mediator.Send(new UpdateBasketItemCommand { Qty = qty, Id = id });

            var json = RetrieveBasket(id);
            HttpContext.Response.AddHeader("X-IC-Trigger", $"{{\"ic-trigger-change-basket-item\": [{json}]}}");

            if (popupBasketType == PopupBasketType.NoMessage)
                return new EmptyResult();

            var model = mediator.Request(new BuyersLabelQuery { Id = id, PopupBasketType =  popupBasketType });
            return PartialView("BuyerLabels", model);
        }

```

Now if I remove the `ic-target` on the input control the global trigger works. It seems to me that ic-target and a global trigger does not play ball.

I suspect I am missing something obvious. :)

**Comment by carsongross** [comment]
Can you verify that '#popupBasketType-1' always exists when the response is being handled?

We trigger the event on the target element (maybe not the best decision, but that's what we did) so if it isn't wired into the DOM it won't do anything.

**Comment by rippo** [comment]
Actually I might want to retract this. Basically if the `ic-target` doesn't exist then the global trigger is not called.

I know this sounds strange but I have basket items where I am return HTML markup in some cases but not all.

**Comment by rippo** [comment]
Lets bin this :)
