### ISSUE TITLE
Send ic-select-from-response as part of a request?

### ISSUE THREAD

**Issue by kezabelle** [LeadDyno/intercooler-js#173]
I checked the fora and the issues, but couldn't find anything of note, so ... is there a reason not to send any `ic-select-from-response` value attached the the request, as either a header or a querystring parameter? If present, it would allow for the server to potentially pare down the response being delivered based on the client's hint. So the backend service could return a full (or partial) response, and then a middleware could reduce that down further, and then Intercooler could (if necessary) do the same.

As it stands, its possible to return the whole page's (rather than a separate partial) HTML content and use `ic-select-from-response` to progressively move towards partials. This is nice because it allows for slowly implementing on top of an older system. By allowing the server to have more involvement in the response, it could be further refined.

**Comment by carsongross** [comment]
It's a good idea, but I always like to push back a bit on things like this to see how necessary it is:  when I use intercooler I often check to see if the `ic-request` request parameter is present and render a stripped down version of the content if so.

Why isn't this good enough?  (I have my reasons, I'd like to hear yours.)

**Comment by kezabelle** [comment]
So, `ic-request` is enough to know on a per-request basis whether a template may be replaced with a partial/stripped down version of the request. But it still requires active intervention to do so; a developer has to opt-in on a per-page/controller/view basis and knowingly make the change.

One of the nicest things (IMHO) about Intercooler's featureset (beyond being a simple declarative attribute way of handling AJAX) is that its possibly to progressively enhance an existing app by leveraging `select-from-response`. So I can do things like attach an `post-to` to a form and use `select-from-response` to replace the whole form, giving the illusion of complex inline validation without doing any, or doing a full page reload (along with the teardown and setup rendering, multiple requests for assets potentially, etc)

If `select-from-response` were provided to the server, I'd be able to apply a middleware over a response, and if the request were intercooler driven, I could use a library to parse the response and filter out the target, and re-wrap it in a `<div>` or `<span>` (so that the inner html is correct) automatically so that Intercooler received the minimal response it needs to fulfil the replacement.

This isn't something I *need* as such, but it would offer more opportunity for the server to intervene, and is something I'd probably make use of in a reusable Django app I'm writing for Intercooler related functionality (so far just a couple of middlewares), and could offer an easier plug-and-play happy path for integration with extant projects.

**Comment by OvermindDL1** [comment]
As a comparison implementation, the Unpoly.js library as the `up-target` attribute, so you can do, say, `up-target="#blah"` and it will replace the element with the id of `blah` in the current document with the one of `blah` in the next document, multiples can be separated with spaces, any selector works so if you select, say, `".blah"` then it will replace all elements with the class of `blah` on this page with the ones from the next in the same order that they appear, removing as necessary but will not add.  It would be a useful feature to add here.  :-)

The unpoly.js documentation for `up-target`:  http://unpoly.com/a-up-target

**Comment by carsongross** [comment]
Alright, I'm convinced.  I'll implement it now.
