### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by onigetoc** [LeadDyno/intercooler-js#174]
What is missing with intercooler is a cool demo app.

With some ajax/json request.

Loading a list of users, click a user and get user informations.

Using this: https://randomuser.me
or this: https://jsonplaceholder.typicode.com
as examples

**Comment by carsongross** [comment]
That sounds great.  Can I ask you to start work on it?  ;)

**Comment by onigetoc** [comment]
Hi, not really, i want it to learn.
For example, i learned Ionic and Angular because Ionc have a lot of demo to start with.
I would never learned it or even started with it if there's was not multiples demos

**Comment by carsongross** [comment]
What do you think of this demo app:

https://sparktutorials.github.io/2016/06/26/ajax-without-writing-javascript.html

**Comment by onigetoc** [comment]
I should had write it before.
when i asked for a demo i wanted to write.
Anything except a todo list.
