### ISSUE TITLE
ic-include parses single item JSON list but not multiple items JSON list

### ISSUE THREAD

**Issue by AmmsA** [LeadDyno/intercooler-js#189]
Doing the following, when `ic-include` is a multiple item JSON list, will result in an error
```
<input type="hidden"
     ic-include='[8, 9]'
     ic-post-to="/event/some_id/day_clicked"
     ic-trigger-from="#day_label">

```

but works if the JSON list contains one element only

```
<input type="hidden"
     ic-include='[8]'
     ic-post-to="/event/some_id/day_clicked"
     ic-trigger-from="#day_label">

```

`[8, 9]` is valid and parsed when you do `var obj = jQuery.parseJSON( '[8 ,9]' );`

Can you do multiple items JSON lists in `ic-include`?

**Comment by carsongross** [comment]
You have to create a JSON object, so that there are names for the submitted variables.
