### ISSUE TITLE
ic-after-target-updated?

### ISSUE THREAD

**Issue by AmmsA** [LeadDyno/intercooler-js#190]
I know there is `ic-on-complete` that can be triggered after the AJAX call is completed, but is there something that can be triggered after the `ic-target` element is updated?

**Comment by SlinSo** [comment]
Here is an example to convert your select elements to "chosen" elements after the replacement is finished with a global ready handler.

``` 
Intercooler.ready(function ($elt) {
    $elt.find('.chosen').chosen();
}
```

**Comment by carsongross** [comment]
Yep @SlinSo 's example is the right thing.
