### ISSUE TITLE
Make "ic-action" aware of success / complete / error events by introducing ic-action-on-X

### ISSUE THREAD

**Issue by rdewell** [LeadDyno/intercooler-js#195]
ic-action would be useful in far more circumstances if it was aware of events.

Introduce corresponding new attributes:

- ic-action-on-complete
- ic-action-on-error
- ic-action-on-success

(corresponding to existing similarly named attributes)

This also ties in with the purpose of #160, since ic-action-X avoids inline Javascript in additional cases.

**TBD**:  Does each needs its own ability to override "ic-action-target"?  So ic-action-target would be considered the default, however it could be override with e.g." ic-action-on-complete-target".

**Comment by machinae** [comment]
+1. This would be hugely useful for common use cases like opening a modal when its contents have been AJAX loaded.

An alternative approach might be to add an **ic-action-on** attribute that mimics ic-trigger-on syntax with special events 'success', 'error', 'complete', etc.

**Comment by ygwain** [comment]
+1

**Comment by rdewell** [comment]
Looks like this was just added in 1.2.x, I believe...

http://intercoolerjs.org/attributes/ic-action.html

```
There are four additional action attributes:
ic-action-beforeSend ic-action-success ic-action-error ic-action-complete
These actions are fired during the jQuery AJAX life cycle.
```
