### ISSUE TITLE
Triggering Intercooler requests on bootstrap modal open

### ISSUE THREAD

**Issue by AmmsA** [LeadDyno/intercooler-js#199]
Bootsrtap allows you to open a modal [see here](https://v4-alpha.getbootstrap.com/components/modal/#live-demo) in the same page. Is there a way to let intercooler trigger a request once the modal is opened the first time?

**Comment by n3storm** [comment]
I tried that and couldn't. Intercooler.js community recommended (can't remember if in Google Group) using Bootstrap Dialog (1) instead to easily trigger first ajax request (Loading remote page section) and use intercooler from there.

1: https://nakupanda.github.io/bootstrap3-dialog/

I am very happy with the solution though some times I need to reload Intercooler Nodes after dialog have been opened.
