### ISSUE TITLE
Http headers encoding problem

### ISSUE THREAD

**Issue by TurningTide** [LeadDyno/intercooler-js#202]
Hello! I'm using Yii2 framework for my backend. As their pjax component is no longer maintained, i dicided to try intercooler. It's great! But first problem i faced is problem with setting titles through "X-IC-Title" header. Since http headers only support ISO-8859-1 encoding, my russian titles were screwed.

So i found a solution in urlencoding X-IC-TITLE header and changing line
`document.title = (xhr.getResponseHeader("X-IC-Title")`
to
`document.title = decodeURI(xhr.getResponseHeader("X-IC-Title"))`

It works fine. So i hope it will help :)

**Comment by carsongross** [comment]
I can't merge that into the main line, but I'm glad the fix was easy!
