### ISSUE TITLE
Intercooler's CDN doesn't support crossorigin/integrity checks

### ISSUE THREAD

**Issue by jsampson-gw** [LeadDyno/intercooler-js#213]
I'm trying to add crossorigin and integrity attributes to all of the CSS and JS resources that my project gets from CDNs. In the case of Intercooler, that looks like this:

`<SCRIPT src="http://cdn.intercoolerjs.org/intercooler-1.1.2.min.js" integrity="sha384-NLFLtSEhkAcJ3fF4aBB6yNp4U2BmG+eRjKv9qKYfdGEC4ofH+1W4X81KL18xiBBx" crossorigin="anonymous"></SCRIPT>`

This fails in Chrome with the following error: 

`Access to Script at 'http://cdn.intercoolerjs.org/intercooler-1.1.2.min.js' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

For reference, both Bootstrap's and jQuery's CDNs return a catch-all CORS policy header like this:

`Access-Control-Allow-Origin: *`

Can you enable that header on Intercooler's CDN?

**Comment by carsongross** [comment]
I think I've enabled it:

![image](https://user-images.githubusercontent.com/469183/29149772-25199e78-7d2b-11e7-91ba-87f2d370010c.png)

**Comment by jsampson-gw** [comment]
Yep, it's working now! Awesome.

By the way, the integrity value I originally put in the description was incorrect due to being mid-debugging (changed one character to see if I got different errors). I've fixed it in the description. I had been getting the original error both with the correct and incorrect integrity values.
