### ISSUE TITLE
Simple execution of a JS function with intercooler

### ISSUE THREAD

**Issue by tiglui96** [LeadDyno/intercooler-js#216]
Hi!
I'm looking for a way to run a simple JS function with Intercooler to use the ic-trigger-on = "load".
For various reasons I can't use document.ready standart function.
There is a way to do that with an IC attribute?

Thanks in advance!

**Comment by carsongross** [comment]
Sorry it took me so long to respond to this: I guess you could combine the ic-action="yourFunction()" and ic-trigger-on="load" attributes to accomplish this...

**Comment by tiglui96** [comment]
Thanks! It worked
