### ISSUE TITLE
Adding jQuery event handlers alongside IC feels wrong; behaves incorrectly

### ISSUE THREAD

**Issue by bobwaycott** [LeadDyno/intercooler-js#222]
First off, I want to say I'm a fan of Intercooler, and your thought-processes and approach are really in sync with my own. Mostly enjoying IC, but running into a situation for which there seems to be no proper way to handle based on what I'm seeing in the docs in a non-breaking way. Seems there's some kind of disconnect/breakage of registering event handlers with jQuery when using Intercooler, and the handlers fail to register on elements loaded via IC requests. This ultimately is making both IC & jQuery feel broken/wrong, and probably shouldn't be happening this way.

### The scenario

There are two lists. `list1` loads *with* the page, complete with IC attrs set. When a user clicks on an item in `list1`, a request is made to load `list2`, a sub list of objects filtered by the `list1` choice, which are then loaded into an existing div available on page load, while each ajax-loaded item also has IC attrs set.

Click handlers are registered via `$(document).ready` to allow for UX changes, while delegating AJAX & DOM updating to IC. The UX changes do not fit within some of the admittedly nice triggers IC provides, because we're doing the opposite&mdash;e.g., when an item in `list1` is clicked, we're toggling all the *other* list items off so only the clicked item remains visible. Same for items in `list2`; we're adding/removing classes on both the clicked element, plus all of its siblings. Those details are bit less relevant, but they explain why there's a need for properly registering/activating click handlers to do more than it appears IC is built for.

### A quick code sample

*Initial load, with `list1` present on load*

```html
<div id='list1' ic-on-beforeTrigger="return !elt.hasClass('active')">
  <a href='' ic-get-from='/list1-url' ic-target='#list2'>
        list1 item
  </a>
</div>
<div id="list2"></div>
<div id="detail"></div>
```

*Post IC-request markup, `list2` now has children present*

```html
<div id='list1' ic-on-beforeTrigger="return !elt.hasClass('active')">
  <a href='' ic-get-from='/list1-url' ic-target='#list2'>
        list1 item
  </a>
</div>
<div id="list2">
  <a href='' ic-get-from='/obj-url/123' ic-target='#detail'>
        list2 item
  </a>
</div>
<div id="detail"></div>
```

### The problem

Now, using IC alongside jQuery, something pretty bad is happening that is killing jQuery event handler registration. Given the following simple handlers, `list2` items are never triggering their expected click handler (but they are triggering their IC-attr-defined ajax actions).

**Standard jQuery Option 1:** *(this should work)*

```js
$(document).ready(function() {
  $('#list1').on('click', 'a', function() {
    console.log('click list1 item');
  });

  $('#list2').on('click', 'a', function() {
    console.log('click list2 item');
  });
});
```

*Result: neither click handler triggers*

**Option 2:** *(this should also work)*

```js
$(document).ready(function() {
  $('a', '#list1').on('click', function() {
    console.log('click list1 item');
  });

  $('a', '#list2').on('click', function() {
    console.log('click list2 item');
  });
});
```

*Result: `list1` click handler triggers; `list2` does not*

### Bonus

I dug around through a few issues that have touched on some funky event handling occurring alongside IC. I've seen a couple mentions of using `Intercooler.ready` as a replacement for `$(document).ready`, even though this feels a bit wrong that `$(document).ready` would require a replacement. However, I've tried it (though could be doing it wrong, as there don't appear to be any direct examples in the docs on expected usage):

```js
Intercooler.ready(function() {
  $('a', '#list1').on('click', function() {
    console.log('click list1 item');
  });

  $('a', '#list2').on('click', function() {
    console.log('click list2 item');
  });
});
```

With it, I can get event handlers to register, however, it's only the variant of `$('a', '#list').on('click' ...` that gets picked up. The other variant, which is afaik valid, fails to register. Worse yet, when attached via `Intercooler.ready`, the events are fired more than once, in an increasing step each time:

- First click? 1 click event fired
- Next click? 2 events fired
- Next click? 3 events fired.
- and so on forever

### Conclusion

IC is fantastic for ajax-driven requests, but when someone also wants to register `click` handlers on IC-enabled elements, things get crazy, jQuery stops working as one expects, and that doesn't feel right. IC should register its actions in a non-breaking way, or provide a direct passthrough to registering handlers on an element for situations where the built in attrs do not provide the UX-focused manipulation a developer needs/requires. For lack of a better example, there are the `ic-on-beforeSend` and `ic-on-beforeTrigger` elements. An attr like these, but intended for UX actions, not Ajax manipulation/cancelling/modification would be pretty excellent. Especially if it could be just to invoke a dev/app-defined function that expects the triggering element. For example, if you want to have something like this happening:

`$(this).toggleClass('active').siblings('a').removeClass('active').toggle();`

There's no easy way to get there without your own click handler. And that UI feedback might change as a designer wants it to, or any other reasons, and the declarative bit of doing something like `ic-action` just doesn't fit here (or i've misunderstood how it's supposed to work, though the docs say it can only call jQuery functions).

Anyway, **tl;dr** > IC appears to break registering jQuery event handlers, and that feels pretty wrong and totally short circuits using jQuery as an awful lot of devs might expect to.

**Comment by bobwaycott** [comment]
Okay, after some more messing around, this way of registering the event handlers works without duplicate events triggering if `stopImmediatePropagation` is used. Still feels pretty wrong to have to handle events like this:

```js
$(document).ready(function() {


  $('a', '#list1').on('click', function(e) {
    console.log('list1 child click');
    e.stopImmediatePropagation();
  });

  // Intercooler ready needed for these methods since they are injected
  Intercooler.ready(function() {

    $('a', '#list2').on('click', function(e) {
      console.log('list2 child click');
      e.stopImmediatePropagation();
    });

  });

});
```

So, it appears ajax-loaded items need to have additional handlers specified inside `Intercooler.ready`, whereas `$(document).ready` works fine for elements that are available in-page on load. 

I think, at the very least, IC's docs could use a bit of mention of this caveat to save other devs time & effort figuring out the right way to handle events when IC is in the page.

Ideally, this may be something worth not only spelling out far more clearly in the docs, but could be a place for an IC attr that can be used to register custom UX-focused handlers that are more than the simple cases already covered by `ic-action` (or `ic-action` could be improved/documented for how to handle complex UI updates via the attr).

I'll leave the issue open for now, as I'd be interested in hearing your feedback on this.

**Comment by carsongross** [comment]
Hey Bob,

I think the problem might be that you are using global registration of events:

```
    $('a', '#list2').on('click', function(e) {
      console.log('list2 child click');
      e.stopImmediatePropagation();
    });
```

`$('a', '#list2')` searches the entire document, but the problem here is that you are going to re-add event handlers to everything every time intercooler loads in a new partial.

I would write the code you have like this:

```
  Intercooler.ready(function(elt) {
    elt.find('a', '#list2').on('click', function(e) {
      console.log('list2 child click');
    });
  });
```

Note that this is not in a `$(document).ready` function, this is top level.  

`Intercooler.ready` basically works the same as `$(document).ready`, but it passes is the partial element that has been swapped in as an argument, so you can add in your event handlers in the new content.  It will also be run against the whole document when the initial page is loaded, so it is a drop in replacement for `$(document).ready` when you want to use intercooler.
