### ISSUE TITLE
The Drag and Drop demo does not work

### ISSUE THREAD

**Issue by rathboma** [LeadDyno/intercooler-js#228]
Hey guys,

I was browsing the docs and noticed the drag and drop example with Sortable.js does not work:
http://intercoolerjs.org/examples/sortablelist.html

Sure its a simple fix!

**Comment by artjomsimon** [comment]
PR #242

**Comment by batisteo** [comment]
Seems fixed by #242

**Comment by carsongross** [comment]
yep!  Thanks for pointing that out :)
