### ISSUE TITLE
ic-action-success method invocation behaviour not the same as ic-action

### ISSUE THREAD

**Issue by jvosloo** [LeadDyno/intercooler-js#230]
I expect:

`ic-action="removeAClass: '#userTokenHolder', 'hide'"`

and 

`ic-action-success="removeAClass: '#userTokenHolder', 'hide'"`

to perform the same action, ie. call a custom method called "removeAClass", passing 2 params to the method in the process.
It works like this for `ic-action`, but not `ic-success-action` ?

**Comment by timb07** [comment]
There's a [documentation bug](https://groups.google.com/d/msg/intercooler-js/s0K3YW7mLEo/rgKArfy6AQAJ): it should be `ic-success-action` instead of `ic-action-success`.

I'll be submitting a fix for this soon.
