### ISSUE TITLE
Trigger swapping mechanism has ended

### ISSUE THREAD

**Issue by Spica2** [LeadDyno/intercooler-js#231]
after.success.ic(evt, elt, data, textStatus, xhr, requestId) is documented with: After headers are processed and the swapping mechanism has begun

I need to call a function when the swapping mechanism has ended.

For now I am calling the function with pushUrl.ic, as it seems to be called when the swapping has ended. But this is not really satisfying eg if you dont use pushUrl.

**Comment by carsongross** [comment]
You can use the Intercooler.ready() function to register a callback that will be executed after every request, with the root content element swapped in.  (I will add some docs to for this to the main documentation page, it comes up.)
