### ISSUE TITLE
How to pass local javascript variable into intercooler request

### ISSUE THREAD

**Issue by svsaraf** [LeadDyno/intercooler-js#257]
First of all, intercooler is amazing, great work! I'm making an app that stores data in javascript locally, and am having a hard time passing information from a local js variable into intercooler. 

The data can be retrieved in javascript using:
`editor.getValue()`

The code I'm currently using (which doesn't appear to work):
`<a class="submitbutton" ic-post-to="/create/" ic-include='{ "name": editor.getValue() }' href="#" ic-target='#message'>
    publish!
</a><div id="message" style="display: inline-block; margin-left: 15px;"></div>`

Regular JSON values seem to work ok ({ "name": "john" } works fine). Any advice on how to do this "the intercooler way"? I could probably force things by manually doing the ajax request in Jquery, for instance, but would like to avoid that.

Thanks!

**Comment by svsaraf** [comment]
For awareness, ended up solving this problem by shoving the editor data into a hidden input in the same form. I suspect this solution isn't ideal though.

https://stackoverflow.com/questions/8963855/how-do-i-get-value-from-ace-editor

**Comment by carsongross** [comment]
hmm, I don't want to change the way ic-include works to use eval, so I think the solution you came up with is the best one.  Often editors like this will include a hidden input by default with the value of the rich text, but it looks like ace doesn't have that.  Here is a similar example:

https://coderwall.com/p/4lrv6a/ace-editor-form-submit

glad you are finding intercooler useful
