### ISSUE TITLE
Double <script> call during update

### ISSUE THREAD

**Issue by matdrapeau** [LeadDyno/intercooler-js#26]
I discovered that during execution of the "processICResponse", the content of the element being updated is set twice. This makes everything inside the ```<script>``` tag executed twice as well.

This is called first:
```
var dummy = $("<div></div>").html(newContent);  #line 753
```
and then this (https://github.com/LeadDyno/intercooler-js/blob/master/src/intercooler.js#L60):
```
transition.newContent(target, newContent, false, function () {  #line 757
    ....
        newContent : function(parent, newContent, isReverse, after){  #line 58
               parent.fadeOut('fast', function(){  #line 59
               ---> parent.html(newContent);  #line 60
```

**Comment by carsongross** [comment]
Fixed a while ago
