### ISSUE TITLE
polling with setInterval

### ISSUE THREAD

**Issue by matdrapeau** [LeadDyno/intercooler-js#27]
https://github.com/LeadDyno/intercooler-js/blob/master/src/intercooler.js#L519

Wondering if it should use setTimeout instead to avoid call stacks? or maybe create another attribute to give the choice?

**Comment by carsongross** [comment]
I somewhat fixed this issue by not issuing more than one request for an element at a time.  We also queue one additional poll.  This actually works out pretty well for this issue.
