### ISSUE TITLE
Anyway to fetch just a page fragment?

### ISSUE THREAD

**Issue by DistinctiveThemes** [LeadDyno/intercooler-js#33]
Hey there

This thing is very cool! But im wondering if there is any way to just fetch a fragment of a given URL rather than the whole thing?

Iv tried the version currently in the pull requests but it does not work for me sadly

Thanks, Danny

**Comment by carsongross** [comment]
Hi there.

Can you explain what you mean by the fragment of a given URL?  An example would be great.

**Comment by DistinctiveThemes** [comment]
Im so sorry for being vague!

Basically, im using this to load data from another page, the contect of which is a blog.

When the user clicks read more on a blog post, this awesome plugin loads the full post content, replacing the smaller preview of the post live on the page, and frankly, its working great and SO SO simple for me to work with. However what id like is rather than prepare the single-post into a separate file (minus head etc, just the bare post/comments) id like to simply target a full blog post, but only grab the 'post-content' 

Basically, it seems like this pull would do it https://github.com/LeadDyno/intercooler-js/pull/29 as I could simply supply the full post url like this - ic-src="a-blog-post.html#post-content" - kinda like a regular ajax or jquery .load function would work

Im probably not using this as it was intended and im willing to accept that as it would be totally my fault, but before I try and get my head round doing this with jquery I thought id at least as the question in case im being truly dumb and missing something (iv spent all day getting to this point, and this thing so fluid and smooth it hate to have to drop it and start again)

I really hope this makes some sense, and thanks for your time!

With the history support you have now added (though im yet to really work out how the heck id implement this) I really do love how you have made this so easy to use!

Cheers, Danny

**Comment by carsongross** [comment]
Ah, I finally understand that pull request now. :)

OK, I'm going to reimplement that functionality and give @ruricolist credit for it, since it was his idea.

Currently, the way this "should" be implemented is by checking on the server side if a request is from intercooler (by looking for the 'ic-request' parameter) and rendering the partial view, rather than the whole view. But in situations like you describe, that's probably a pain.

No guarantees on when I'll get it done, but it will be my next project.

**Comment by DistinctiveThemes** [comment]
Thanks so much! Happy to wait :)

Once you have used intercooler, everything else just seems overly complex to me, this really is some incredible work. Im sure id love it even more if I was using it for what it was intended lol

**Comment by flashtopia** [comment]
does the ic-request param work now?  and how about a server request header instead for better seo?

**Comment by carsongross** [comment]
ic-request param should be going up, and we use a header as well.  It's all added dynamically during the ajax call, so it shouldn't have any effect on SEO.

**Comment by carsongross** [comment]
See https://github.com/LeadDyno/intercooler-js/commit/2823151ef769f2572f587e9ac51f63796f6aaba8

**Comment by DistinctiveThemes** [comment]
:D Thank you!!

Works wonderfully!!!!!
