### ISSUE TITLE
ic-get-from not working when using target element

### ISSUE THREAD

**Issue by knutb** [LeadDyno/intercooler-js#34]
This does not work (the ictarget node remains unchanged when the a is clicked):

     <a ic-get-from="/myapp/test1" ic-target="#ictarget" ic-push-url="true">Click me!</a>
     <div id="ictarget"></div>

But this does:

    <a ic-post-to="/myapp/test1" ic-target="#ictarget" ic-push-url="true">Click me!</a>

    <div id="ictarget"></div>

What am I doing wrong?

**Comment by carsongross** [comment]
I just added a test for this case, and it worked fine:

https://github.com/LeadDyno/intercooler-js/commit/243f155c61ca4ef1a9c4b2466460c1ff62878782

What version of intercooler are you using?

**Comment by carsongross** [comment]
Also, can you confirm the response text for the GET?

**Comment by carsongross** [comment]
Closing for lack of response
