### ISSUE TITLE
support install from composer.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [LeadDyno/intercooler-js#35]
Good morning, good module, you could add installation via composer, to be used in php.

**Comment by usualdesigner** [comment]
For what? This is not PHP package.

**Comment by gruberro** [comment]
What about support for bower?

**Comment by carsongross** [comment]
I definitely need to create a bower package for intercooler.  

I’m planning on a point release this Friday and will try to publish one then.

Cheers,
Carson

On April 7, 2015 at 9:36:35 AM, Robert Gruber (notifications@github.com) wrote:

What about support for bower?

**Comment by tecnologiaterabyte** [comment]
+1 👍

**Comment by gruberro** [comment]
That would be great. Please let me know if I can support you somehow!

**Comment by carsongross** [comment]
Bower support will be made available on Friday
