### ISSUE TITLE
InterCooler vs Defunkt/Jquery-Pjax

### ISSUE THREAD

**Issue by flashtopia** [LeadDyno/intercooler-js#38]
Hello.
Can you please provide a breakdown of Intercooler vs Github/Defunk Pjax.
It seems like both follow the same concept, but yours is easier to use.
Just curious what are the benefits of intercooler over, and weaknesses as compared.
Might be useful for those picking up intercooler on new projects.

https://github.com/defunkt/jquery-pjax

**Comment by carsongross** [comment]
Intercooler was inspired by both Pjax and Turbolinks, but is a more complete AJAX library.  Both of those systems are tied more to AJAX-based navigation, with history support.

Intercooler can do that, but it also provides support for things like form submissions via POSTs, AJAX calls that you don't want to participate in history (i.e. mutating requests), polling, custom header support for client side event firing and redirection, and so on.

So, as of right now, intercooler is a more complete tool set for doing general partial-based AJAX programming.  Extends and generalizes both of those excellent libraries.  And, of course, it can interoperate with either of them.
