### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by fcamp** [LeadDyno/intercooler-js#39]
I'm not able to use IC with form validation in the proper way.
I tried 2 approaches. 

##### Validation function that returns false if not valid, as I read here https://groups.google.com/d/msg/intercooler-js/EINwxcOO2h8/q00B3p8_jrAJ

The problem here is that the request is sent even if myValidation returns false
```html
<form ic-post-to="/my/url" ic-on-beforeSend="myValidation()">
  <button>Submit</button>
</form>
```

```javascript
function myValidation() {
   return false;
}
```

##### Another way I tried to validate the form. 
Here the idea is to block the current request if the form is not valid and sent another req once it is valid.

I'm able to block the request the first time, but then, when my fake form become valid, I cannot send it. 

```html
<form ic-post-to="/my/url" ic-on-beforeSend="myValidation(xhr)">
  <button>Submit</button>
</form>
```

```javascript
valid = false;
function myValidation(xhr) {
  if(! valid){//the first time is invalid
    xhr.abort();
    valid = true;//from the second time is valid
  }
}
```

Can you give me any advice about this?
Thanks

**Comment by fcamp** [comment]
I noticed that, once I abort the request, then `on-beforeSend` callback is not even called anymore.

That happens because the `ic-request-in-flight` flag remains set to true;
As (ugly) workaround, I reset that flag after I abort the request.

```html
<form id="my-form" ic-post-to="/my/url" ic-on-beforeSend="myValidation(xhr)">
  <button>Submit</button>
</form>
```

```javascript
valid = false;
function myValidation(xhr) {
  if(! valid){//the first time is invalid
    xhr.abort();
    //resetting the in-flight flag
    $("#my-form").data('ic-request-in-flight', false);
    valid = true;//from the second time is valid
  }
}
```
Now it works as expected.
I don't know if, at this stage, there is a better way to do this, but I'm sure I should not set the  `ic-request-in-flight` as it seems for internal use only.

**Comment by carsongross** [comment]
Hmm, I should have thought of that!

We reset the ic-request-in-flight data in the 'complete' block of the AJAX request, which, according to this documentation, should always be called:

  http://api.jquery.com/jquery.ajax/

I will write some tests around this use case (and implement the return false behavior we've discussed previously) for the 0.4.5 release.

Thanks,
Carson
