### ISSUE TITLE
Demo click does not trigger on Android Tablet only on Ipad

### ISSUE THREAD

**Issue by lpnkng** [LeadDyno/intercooler-js#42]
I tested on Android 4.4.2 samsung tablet and ipad. Ipad is ok but impossible to click on Android tablet

**Comment by carsongross** [comment]
Are you able to debug?  Are there any javascript errors?

I will try to test later today.

**Comment by carsongross** [comment]
Closing, unable to reproduce.  If you can reproduce and give me platform info I'm happy to look at it.
