### ISSUE TITLE
in this case the complete event is not triggered when the defaultTransition is none

### ISSUE THREAD

**Issue by rgroli** [LeadDyno/intercooler-js#44]
I noticed that the complete event is not triggering when the the defaulttransition is set to "none" **and** the reponse from the server contains the triggering element itself again. 

##### HTML
```html
 <div id="selftarget">
   <a ic-target="#selftarget" ic-get-from="/api">click me! (self targeted)</a>
</div>
<a ic-target="#externaltarget" ic-get-from="/api">click me! (external target)</a>
  <div id="externaltarget"></div>
```
##### JS
```javascript
    $(function(){
      Intercooler.defaultTransition("none");

      $.mockjax({
        url: "/api",
        responseText: '<a ic-target="#selftarget" ic-get-from="/api">click again</a>'
      });

      $(document).on('beforeSend.ic', function(){
        alert('beforeSend')
      }).on('complete.ic', function(){
        alert('complete')
      });
    })
```

Whithout setting the defaultTransition to none all events are triggered as expected. "beforeSend" is always triggered.

**Comment by carsongross** [comment]
Fun fun.  :)

Can you create a test case in unit_tests.html and I’ll try to fix it?

Cheers,
Carson

On April 11, 2015 at 1:34:28 PM, Oliver (notifications@github.com) wrote:

I noticed that the complete event is not triggering when the the defaulttransition is set to "none" and the reponse from the server contains the triggering element itself again.

HTML

 <div id="selftarget">
   <a ic-target="#selftarget" ic-get-from="/api">click me! (self targeted)</a>
</div>
<a ic-target="#externaltarget" ic-get-from="/api">click me! (external target)</a>
  <div id="externaltarget"></div>
JS

    $(function(){
      Intercooler.defaultTransition("none");

      $.mockjax({
        url: "/api",
        responseText: '<a ic-target="#selftarget" ic-get-from="/api">click again</a>'
      });

      $(document).on('beforeSend.ic', function(){
        alert('beforeSend')
      }).on('complete.ic', function(){
        alert('complete')
      });
    })
Whithout setting the defaultTransition to none all events are triggered as expected. "beforeSend" is always triggered.

**Comment by carsongross** [comment]
Fixed.  Now fire the event on the body, since the element itself may no longer be part of the dom.  See 2ea51480c9e651288b01ca09fc7cfa433fec5c92
