### ISSUE TITLE
Give a onpopstate event handler

### ISSUE THREAD

**Issue by dudheit314** [LeadDyno/intercooler-js#47]
When using Intercooler the `window.onpopstate` event is overwritten. How could I get a callback when user clicks the go back button in browser?

**Comment by carsongross** [comment]
I will add some events around the history support.  I actually need them as well.  :)

Cheers,
Carson

On April 15, 2015 at 2:30:16 AM, dudheit314 (notifications@github.com) wrote:

When using Intercooler the window.onpopstate event is overwritten. How could I get a callback when user clicks the go back button in browser?

**Comment by carsongross** [comment]
see onpopstate.ic docs in 2ea51480c9e651288b01ca09fc7cfa433fec5c92
