### ISSUE TITLE
localStorage overflow

### ISSUE THREAD

**Issue by dudheit314** [LeadDyno/intercooler-js#48]
When using the history feature with big responds and multiple page queries I get a localStorage overflow. The history function is stop working than until I execute `localStorage.clear();` 
It would be good if Intercooler removes old history states if the localStorage is close to overload.

**Comment by carsongross** [comment]
Yep, I saw this same problem as well.  I’m working on a fix, hopefully out by Friday.

Cheers,
Carson

On April 15, 2015 at 3:59:26 AM, dudheit314 (notifications@github.com) wrote:

When using the history feature with big responds and multiple page queries I get a localStorage overflow. The history function is stop working than until I execute localStorage.clear();
It would be good if Intercooler removes old history states if the localStorage is close to overload.

**Comment by carsongross** [comment]
Fixed in 2ea51480c9e651288b01ca09fc7cfa433fec5c92
