### ISSUE TITLE
New event indicating the end of a transition

### ISSUE THREAD

**Issue by rgroli** [LeadDyno/intercooler-js#49]
The event "complete.ic" fires before the actual transition ends. Sometimes it is required to execute a callback to initialize parts of the ui which were just fetched. Sometimes the initialization requires the fetched ui to be visible. "complete-ic" fires when the transition might not be finished and the ui is still invisible or in the process of fading in. 

Could "complete.ic" be fired after the transition?
Or could there be a new event introduced indicating the end of the transition?

**Comment by koichirose** [comment]
I had this issue, too. Had to dig in the source code to find out there's the 'complete_transition' event and used that one to be sure that the content IC asks for is available in page.
Maybe it should be mentioned in the documentation.

Also, I'm now wondering what would happen when there are no transitions involved (if possible).
