### ISSUE TITLE
[Feature Request] handle CORS

### ISSUE THREAD

**Issue by brainztorm** [LeadDyno/intercooler-js#52]
It could be cool if intercooler could handle CORS request (http://www.html5rocks.com/en/tutorials/cors/#toc-cors-from-jquery) transparently like :
```
<button ic-post-to="https://the_other_domain.com/target_url"> Click Me! </button>
```

**Comment by carsongross** [comment]
Looking at this issue, is there anything intercooler needs to do?  Seems like you should just be able to support it with the normal jQuery mechanisms, right?  There is no constraint on the ic-src attribute being relative, although most examples are like that....

**Comment by brainztorm** [comment]
You're right, thanks Carson.
Have a good day !
