### ISSUE TITLE
File upload : the enctype of the request is not switching to "multipart/form-data"

### ISSUE THREAD

**Issue by brainztorm** [LeadDyno/intercooler-js#54]
Form with enctype="multipart/form-data" like : 

```
<form ic-post-to="/save_image" ic-target="#image_place" enctype="multipart/form-data"> 

<input type="file" name="image"> 
<button type="submit">upload the image</button> 
                 
</form> 
```
doesn't work, the enctype of the request is not switching to "multipart/form-data"

**Comment by ziscloud** [comment]
+1

**Comment by n3storm** [comment]
Is there any advance on this? I am using release 0.9.1 and is still not working.

**Comment by carsongross** [comment]
Hi Nestor,

Sorry, I haven't had time to look at it.  It looks like the right solution is to use FormData:

http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax

but it will involve some annoying changes to the way we create requests.  I will try to get to it this month.

Thanks,
Carson

**Comment by brainztorm** [comment]
Thanks Carson !

**Comment by n3storm** [comment]
Thanks Carson. FormData is the solution I found too.
By the way, I tried to hack your library. I found it pretty clear and well documented but I failed due to my lack of experience with "hardcore" javascript. Thanks for creating intercooler.js

**Comment by carsongross** [comment]
Fixed with commit https://github.com/LeadDyno/intercooler-js/commit/bbb41875759d93b5a670b0c5f952841920282f1d

**Comment by brainztorm** [comment]
Cool ! thanks Carson !

**Comment by n3storm** [comment]
Thanks pal!
