### ISSUE TITLE
Jquery closest/find selector support 

### ISSUE THREAD

**Issue by Pandahisham** [LeadDyno/intercooler-js#56]
sometimes in list items it is helpful to have a descentant class selector for target instead of id , something like ic-target ="find .description"

**Comment by Pandahisham** [comment]
oops descendant

**Comment by whoever123** [comment]
You mean like this?  Works fine.

    <button type='button' id='ping' class='btn btn-primary' ic-post-to='/ping' 
           ic-target='#result > .second'>Ping</button>

    <ul id='result'>
        <li>test1</li>
        <li class='second'>test2</li>
        <li>test3</li>
    </ul>

**Comment by webholics** [comment]
I have the same problem. In my opinion intercooler relies to heavily on defining unique global ids for DOM elements. This may work for small examples but not for complex cases where you may have lots of the same ajax components on the same page.

In my option all selectors used in Intercooler attributes should per default not be global but restricted to the children of the current element. And only if you really want to have a global selector you could put the keyword "global" in front of the selector. 

Another thing which really frustrates me is that not all selectors are handled equally e.g. I can use "closest" on ic-target but not on ic-indicator.

**Comment by adaniello** [comment]
In doc you can read "attribute should be a valid global CSS/JQuery selector OR the string closest followed by a space, followed by a valid CSS selector, which will be evaluated as the closest parent matching the given selector".
And, as @whoever123 said, any "valid global CSS/JQuery selector" works fine.

**Comment by webholics** [comment]
Yes but that is not my point. My point is that I want not a global selector (`$(selector)`) but a lokal one (`$(selector, el)`).

**Comment by adaniello** [comment]
Can you use "closest" reserved word (eg "closest div.modal-content")?
Or remember that the attribute may be placed on parent elements.

**Comment by adaniello** [comment]
Why not post a codepen sample?

**Comment by webholics** [comment]
This is my case http://codepen.io/anon/pen/avRrbe

Its just the markup. My problem is that this is a component which is in use multiple times on the page and I don't want to create artifical unique id attributes for `.voting` or `.voting__progress` just to be able to select them.

**Comment by adaniello** [comment]
@webholics, i don't understand well what is your problem, but if you have multiple ".voting" blocks, everyone with its progress, take a look at http://codepen.io/anon/pen/rOqgeb (css is only for sample).
I hope this can help you

**Comment by carsongross** [comment]
Hi webholics.  I can see your point, generating unique IDs in repeated UX is ugly and annoying.  It seems like a sane algorithm would be to try the selector first as a find() from the current element, then as a global selector.

I will try to get something along those lines in the next release.
