### ISSUE TITLE
current app already has jquery, but its not working

### ISSUE THREAD

**Issue by ervishal** [LeadDyno/intercooler-js#57]
in my current application which already has jquery, added intercooler.js also but its not working. anyone can help will be appreciated.

**Comment by n3storm** [comment]
Hi,
you should know how to debug javascript and webapplications before (or while) getting into intercooler or any other web app.

Following is a Firebug guide from IBM, if you use other dev tools or browser you should be able to find a more suitable guide for you:
http://www.ibm.com/developerworks/library/wa-aj-firebug/

Some simple rules:
0. Check all systems involved log files. Setup sytems, apps, servers, browsers up for logging, debug mode, debug tools, etc 
1. If something doesn't work: check if needed resources are being loaded
2. If are loaded and still doesn't work: check error messages in console
3. If are not loaded: check path, urls, routes, resources server log.

Hope it helps.

**Comment by carsongross** [comment]
Intercooler usually will print errors to the javascript console, if it is available.  If you can give me more specifics I can try to help.

Cheers,
Carson

On July 2, 2015 at 12:01:40 AM, Néstor Díaz Valencia (notifications@github.com) wrote:

Hi,
you should know how to debug javascript and webapplications before (or while) getting into intercooler or any other web app.

Following is a Firebug guide from IBM, if you use other dev tools or browser you should be able to find a more suitable guide for you:
http://www.ibm.com/developerworks/library/wa-aj-firebug/

Some simple rules:
0. Check all systems involved log files. Setup sytems, apps, servers, browsers up for logging, debug mode, debug tools, etc
1. If something doesn't work: check if needed resources are being loaded
2. If are loaded and still doesn't work: check error messages in console
3. If are not loaded: check path, urls, routes, resources server log.

Hope it helps.

**Comment by ervishal** [comment]
Thanks for the reply!..  I am using firebug and chrome console but could not find the actual issue. will check and let you know more about it guys!

**Comment by carsongross** [comment]
Closing issue, this should be handled via the newsgroup until an actual bug is uncovered.
