### ISSUE TITLE
HTTPS failure CDN Hosted javascript

### ISSUE THREAD

**Issue by mathieusteele** [LeadDyno/intercooler-js#58]
Tested site with SSL with script linked as "//cdn.intercoolerjs.org/intercooler-0.4.10.min.js" and this file failed to load. Apparently this particular CDN may not support https for this file.

**Comment by mathieusteele** [comment]
Fix is to reference it temporarily as http://cdn.intercoolerjs.org/intercooler-0.4.10.min.js which works when the file that references it is served from either http or https. The preference would be for the CDN to allow a secure connection.

**Comment by carsongross** [comment]
Hey Mathieu,

I haven’t gotten an ssl certificate for intercoolerjs.org yet, so you have to refer to the https CDN version using MaxCDN’s name:

  https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-0.4.10.js 

That works for both https and http, so you can use the protocol-relative trick with it if you like.

Cheers,
Carson

On August 7, 2015 at 8:08:59 PM, Mathieu Steele (notifications@github.com) wrote:

Fix is to reference it temporarily as http://cdn.intercoolerjs.org/intercooler-0.4.10.min.js which works when the file that references it is served from either http or https. The preference would be for the CDN to allow a secure connection.

**Comment by mathieusteele** [comment]
Thank you!
