### ISSUE TITLE
How to parse JSON response?

### ISSUE THREAD

**Issue by ghprod** [LeadDyno/intercooler-js#61]
Hi, 

any idea how to parse json response instead html response?

Thanks

**Comment by carsongross** [comment]
Here is an example that uses a JSON response with twitters typeahead library:

http://intercoolerjs.org/examples/typeahead.html

Intercooler handles the AJAX and passes the data back to the library.

**Comment by ghprod** [comment]
:+1:

Thanks a lot

**Comment by ghprod** [comment]
btw i ended with something like this ..

![image](https://cloud.githubusercontent.com/assets/1922652/9935374/6e8a5a4c-5d80-11e5-9caf-fadf65b92453.png)

Thanks

**Comment by carsongross** [comment]
Looks good!   

If you have some time, please tweet, fb post or put up a reddit post on intercooler to get the word out.
