### ISSUE TITLE
Triggers not working after cloning an element

### ISSUE THREAD

**Issue by bribar** [LeadDyno/intercooler-js#65]
I have a menu that I am cloning for mobile purposes. The menu at load time works great with intercooler, but when cloning the menu and adding it to the DOM, intercooler doesn't seem to react to the clicks. Does intercooler need to be reinitialized? Or does it not support this capability?

**Comment by carsongross** [comment]
You'll need to call 

    Intercooler.processNodes(elt)

on the root cloned element to hook things up.  See: 

  http://intercoolerjs.org/reference.html

for the full javascript API.

**Comment by bribar** [comment]
Great thx! Must have missed that while looking through the docs. :(

**Comment by carsongross** [comment]
No worries, cheers.
