### ISSUE TITLE
Trigger on load event not working? (lazy loading)

### ISSUE THREAD

**Issue by paxperscientiam** [LeadDyno/intercooler-js#70]
Hi there!

I've really been having a lot of fun with Intercooler; however, I am having trouble replicating your lazy element loading example, as specified.

http://intercoolerjs.org/examples/lazyload.html

I've been able to generate a mock response by setting "ic-trigger-on" to various mouse events and "scrolled-into-view", but when I set it to "load" I get a 404 error.

Is this a bug? Are the docs out of date? For the record, I am using version #0.9.

Thanks.

**Comment by carsongross** [comment]
If you are getting a 404 on the load action only, but other actions are working, I would guess that mockjax isn't loaded yet to handle the request when the load event is firing.

Maybe move your mockjax initialization above the the intercooler code?

**Comment by paxperscientiam** [comment]
Hi carsongross, thanks for the rapid response!

I looked into that, but I already am loading mockjax before intercooler (using headjs which ensures that). 

Here is the relevant HTML:
````
  <div class="text-center" ic-get-from="/biograph" ic-trigger-on="load" data-no-instant>
            <i class="fa fa-spinner fa-spin fa-2x" ></i>
           </div>
````

Here is the relevant JS:
````
if (window.Intercooler !== undefined && window.jQuery.mockjax !== undefined) {
					          console.log("Intercooler and mockjax are ready!");
					          $.mockjax({
						            url: "/about/eliot/1",
                        responseTime:500,
						            responseText: "Available for hire.",
                        response: function(settings) {
                            console.log("bio1");
                        }
					          });
                    //next
                    $.mockjax({
						            url: "/biograph",
                        responseTime:500,
						            responseText: "<img src='/assets/myself/history.gif'>"
					          });
				        }
````

In your estimation, does anything overtly wrong stand out?

**Comment by carsongross** [comment]
Can you ensure that this code:

$.mockjax({
                                    url: "/biograph",
                        responseTime:500,
                                    responseText: "<img src='/assets/myself/history.gif'>"
                              });
                        }

is run before the load event is triggered?  Make sure it is not in a jQuery onLoad callback.  Maybe just dump it into a script tag directly on the page:

<script>
    $.mockjax({
                                    url: "/biograph",
                        responseTime:500,
                                    responseText: "<img src='/assets/myself/history.gif'>"
                              });
                        }
</script>

Given that the other trigger actions are working, it seems like it has to be a timing issue.

Cheers,
Carson

On December 28, 2015 at 4:04:31 PM, Chris (notifications@github.com) wrote:

Hi carsongross, thanks for the rapid response!

I looked into that, but I already am loading mockjax before intercooler (using headjs which ensures that).

Here is the relevant HTML:

  <div class="text-center" ic-get-from="/biograph" ic-trigger-on="load" data-no-instant>
            <i class="fa fa-spinner fa-spin fa-2x" ></i>
           </div>

Here is the relevant JS:

if (window.Intercooler !== undefined && window.jQuery.mockjax !== undefined) {
                              console.log("Intercooler and mockjax are ready!");
                              $.mockjax({
                                    url: "/about/eliot/1",
                        responseTime:500,
                                    responseText: "Available for hire.",
                        response: function(settings) {
                            console.log("bio1");
                        }
                              });
                    //next
                    $.mockjax({
                                    url: "/biograph",
                        responseTime:500,
                                    responseText: "<img src='/assets/myself/history.gif'>"
                              });
                        }

In your estimation, does anything overtly wrong stand out?

**Comment by paxperscientiam** [comment]
Sorry, could you clarify "jQuery onLoad callback"? Thanks.

**Comment by carsongross** [comment]
Ah, sorry, I'm being loose with my language.  So the "load" action is fired once the page has loaded, using the jQuery "ready" handler:

  https://api.jquery.com/ready/

Are you putting that $.mockjax({...}) code inside a jQuery ready handler, or is it in a top level javascript tag?

Given that things are working when you use other events, my guess is that the

  $.mockjax({...})

code is executing *after* intercooler is firing the request, so mockjax isn't catching it, leading to the 404 (since a real ajax request is being made.)

Does that make sense?

**Comment by paxperscientiam** [comment]
Yes, that does make sense! Thank you @carsongross . I will report back once I've fully heeded your advice.

**Comment by paxperscientiam** [comment]
Hi Carson, I appreciate you working with me here.

Perhaps there is some subtlety I am not grasping?

Here is what I'm working with now:
```javascript
    (function () {
        head.ready( function () {
        if (window.jQuery.mockjax !== undefined && window.Intercooler
!== undefined) {
            //
            console.log("jQuery is ready for mockjax!");
            console.log(document.readyState === 'complete');
            $.mockjax({
	  	          url: "/biograph",
                responseTime:500,
	  	          responseText: "<img src='/assets/myself/history.gif'>"
	          });
        }
        });
    })();
```
`console.log(document.readyState === 'complete')` yields false as
desired; that is the function is fired before the 'ready' event is
fired. Still, I am getting a 404 error.

Mouseover, etc work in this case as well.

Thoughts?

**Comment by carsongross** [comment]
Ah, so that’s the problem: you are initialzing the mockjax handler in the “ready” function of the head element.

You need to move that code out to a top level script block:

<script>
$.mockjax({
url: "/biograph",
responseTime:500,
responseText: "<img src='/assets/myself/history.gif'>"
});
</script>

so that it will execute before all the load events do.

Cheers,
Carson

On December 28, 2015 at 5:23:29 PM, Chris (notifications@github.com) wrote:

Hi Carson, I appreciate you working with me here.

Perhaps there is some subtlety I am not grasping?

Here is what I'm working with now:
```javascript
(function () {
head.ready( function () {
if (window.jQuery.mockjax !== undefined && window.Intercooler
!== undefined) {
//
console.log("jQuery is ready for mockjax!");
console.log(document.readyState === 'complete');
$.mockjax({
url: "/biograph",
responseTime:500,
responseText: "<img src='/assets/myself/history.gif'>"
});
}
});
})();
```
`console.log(document.readyState === 'complete')` yields false as
desired; that is the function is fired before the 'ready' event is
fired. Still, I am getting a 404 error.

Mouseover, etc work in this case as well.

Thoughts?

**Comment by carsongross** [comment]
Closing, we are handling offline.
