### ISSUE TITLE
preventDefault for href

### ISSUE THREAD

**Issue by vrtc** [LeadDyno/intercooler-js#75]
If I use
```html
<a href="/tasks?page=1" ic-target=".wraper-list" ic-scroll-to-target="true"   ic-get-from="/tasks?page=1">1</a>
```
The intercooler is not working, I have to add onclick="return false"

**Comment by carsongross** [comment]
You probably need to change the href to “#"

Cheers,
Carson

On January 22, 2016 at 7:33:29 AM, vrtc (notifications@github.com) wrote:

If I use

<a href="/tasks?page=1" ic-target="wraper-list" ic-scroll-to-target="true"   ic-get-from="/tasks?page=1">1</a>
The intercooler is not working, I have to add onclick="return false"

**Comment by vrtc** [comment]
unfortunately I can't do this, I need in the source code the href is present. This is necessary for indexing by search engines

**Comment by adaniello** [comment]
Only an idea: why not use "href" attribute in place of "ic-[VERB]-to" when "ic-verb" attribute (or also other, eg "ic-target") is defined?
Carson, do you think could be an interesting addition?

**Comment by carsongross** [comment]
I do think that would be a good solution.

I’d like to look at a mode/attribute for intercooler that uses Progressive Enhancement:

  https://en.wikipedia.org/wiki/Progressive_enhancement

where you can transform all your links and forms into intercooler-based AJAX requests using the normal attributes, but they keep working “the normal way” if you don’t have javascript enabled.

Just haven’t had time to work on it.

Cheers,
Carson

On January 22, 2016 at 7:47:27 AM, adaniello (notifications@github.com) wrote:

Only an idea: why not use "href" attribute in place of "ic-[VERB]-to" when "ic-verb" attribute (or also other, eg "ic-target") is defined?
Carson, do you think could be an interesting addition?

**Comment by carsongross** [comment]
OK, I fixed the immediate issue w/ anchor tags in development, will open another ticket for the more general progressive enhancement feature.
