### ISSUE TITLE
prepend and append function undefined elt

### ISSUE THREAD

**Issue by allain** [LeadDyno/intercooler-js#80]
prepend and append functions both attempt to log an error using elt, but elt is not defined in that context.

    log(elt, formatError(e), "ERROR");

should be changed to:

    log(parent, formatError(e), "ERROR");

**Comment by carsongross** [comment]
Great catch.  Want to do it as a pull request so you get credit?

**Comment by allain** [comment]
voila https://github.com/LeadDyno/intercooler-js/pull/81

**Comment by carsongross** [comment]
Thanks!
