### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by accidentalmeme** [LeadDyno/intercooler-js#86]
I set https on my site and when i tried to access a resource using ic-get-from it went to http and got me a mixed content warning.

**Comment by carsongross** [comment]
All ajax requests should be done via relative URLs, so they should preserve the schema.

Can you show me the attribute declaration and the console for the request?

**Comment by accidentalmeme** [comment]
![capture2](https://cloud.githubusercontent.com/assets/7762716/13605734/fb526582-e516-11e5-887a-14ce4df652d7.PNG)
![capture1](https://cloud.githubusercontent.com/assets/7762716/13605735/fb5e6a76-e516-11e5-98ae-e358c550db10.PNG)
Here is the file. It shows the code and the console.

**Comment by carsongross** [comment]
That's bizarre: we are literally just passing the string along to the jQuery .ajax() function, so it should respect the schema of the current page.

Looking at this bug:

http://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire

I wonder if the error message is not correct and it actually is using HTTPS, but then the HTTPS content includes HTTP resources.

Can you look on the network tab and confirm that the request is going up as HTTP?  There is absolutely no reason it should, given my understanding of jQuery!  (Sorry to be so persistent on this.)

**Comment by accidentalmeme** [comment]
![capture4](https://cloud.githubusercontent.com/assets/7762716/13614976/169d1592-e541-11e5-97e4-9477a314c2d4.PNG)
I get a 301 moved permanently which shouldn't happen. The https issue might be that my cdn, Cloudflare isn't handling the request well, considering that my orgin server doesnt have https, it only happens on the reverse proxy, but i have HSTS enabled. The webpage when accessed normally is blank(I havent added any content to the body, its a php script), but a file exists.

**Comment by carsongross** [comment]
OK, it looks like this is a server side issue: the (correct) HTTPS request that intercooler/jquery is issuing is being redirected to another URL and my bet is that either that URL is not HTTPS or it is returning content with non-HTTPS resources within it.

**Comment by accidentalmeme** [comment]
When I access the file normally( typing it in) i get https content so that is weird, Ill look into it.

**Comment by carsongross** [comment]
Closing out since there isn't an update.
