### ISSUE TITLE
new elements

### ISSUE THREAD

**Issue by csimpi** [LeadDyno/intercooler-js#89]
Hi!

If i would like to fire an AJAX request with new DOM element, after click nothing happens. 
I generated a button with dynamically content and it didnt works.

`<button class="text-danger btn-xs" data-id="33" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>`

**Comment by carsongross** [comment]
Can you check your browser console to see if there are any errors logged?

If you create a gist with your code I can look at it.

Cheers,
Carson

On April 3, 2016 at 3:49:31 PM, csimpi (notifications@github.com) wrote:

Hi!

If i would like to fire an AJAX request with new DOM element, after click nothing happens.
I generated a modal with dynamically content and it didnt works.

**Comment by csimpi** [comment]
No errors, and nothing happens in the network tab too.

This code makes a modal with userlist content, from a template file.

`      $(document).ready(function() {

        $('.modal-basic').magnificPopup({
          type: 'ajax',
          alignTop: true,
          overflowY: 'scroll',
          callbacks: {
  parseAjax: function(mfpResponse) {
    console.log('Ajax content loaded:', mfpResponse.data);
    var data = JSON.parse(mfpResponse.data);
    data=data[1];
    var CONTENT ='';
    var template = twig({ id: "conversation-recepients-template", href: "/template/admin/hu-HU/ui-elements/conversation-recepients-template.php", async: false});
    CONTENT =  twig({ ref: "conversation-recepients-template" }).render({D:data,UPLOAD_DIR:UPLOAD_DIR});
    mfpResponse.data = generate_modal({TITLE:'Címzettek listája',CONTENT:CONTENT,CLASS:'',FOOTER:false})

  }
}
        });


        
      });
`

Generated content:
`<section class="panel">
                                            
											<header class="panel-heading">
												<h2 class="panel-title">Címzettek listája</h2>
											</header>
                                            
											<div class="panel-body">
												<div class="modal-wrapper">
                                                    
													<div class="modal-text">
														<ul class="simple-user-list">

    
        <li class="col-md-6 row">
            <div class="col-md-10">
												<figure class="image rounded">
													<img src="/upload/1_avatar_12794700_1864564980436744_9151061640106972004_o.jpg" alt="Administrator" class="img-circle" style="width: 35px;">
												</figure>
												<a href="/users/1" class="title">Administrator</a>
												<span class="message truncate">pitt@jss.hu</span>
            </div>
            <div class="col-md-2">
                <button class="text-danger btn-xs" data-id="33" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
            </div>
		</li>
    
        <li class="col-md-6 row">
            <div class="col-md-10">
												<figure class="image rounded">
													<img src="/upload/default_profile_photo.png" alt="Test UserA" class="img-circle" style="width: 35px;">
												</figure>
												<a href="/users/2" class="title">Test UserA</a>
												<span class="message truncate">u1@user.hu</span>
            </div>
            <div class="col-md-2">
                <button class="text-danger btn-xs" data-id="34" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
            </div>
		</li>
    
        <li class="col-md-6 row">
            <div class="col-md-10">
												<figure class="image rounded">
													<img src="/upload/default_profile_photo.png" alt="Test UserB" class="img-circle" style="width: 35px;">
												</figure>
												<a href="/users/3" class="title">Test UserB</a>
												<span class="message truncate">u2@user.hu</span>
            </div>
            <div class="col-md-2">
                <button class="text-danger btn-xs" data-id="35" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
            </div>
		</li>
    

</ul>
													</div>
												</div>
											</div>
                                            
										</section>`

**Comment by carsongross** [comment]
It’s probably an issue where the HTML is added after intercooler has done it’s processing.  Two things to try:

1) Put the intercooler script below the javascript block that sets up the magnificPopup, which should trigger intercoolers default processing *after* the plugin changes the dom

2) In your existing code, after you call magnificPopup(), put a call in to initialize the newly created HTML: Intercooler.processNodes($(‘.modal-basic’))

Cheers,
Carson

On April 4, 2016 at 11:59:41 AM, csimpi (notifications@github.com) wrote:

No errors, and nothing happens in the network tab too.

This code makes a modal with userlist content, from a template file.

` $(document).ready(function() {

    $('.modal-basic').magnificPopup({
      type: 'ajax',
      alignTop: true,
      overflowY: 'scroll',
      callbacks: {

parseAjax: function(mfpResponse) {
console.log('Ajax content loaded:', mfpResponse.data);
var data = JSON.parse(mfpResponse.data);
data=data[1];
var CONTENT ='';
var template = twig({ id: "conversation-recepients-template", href: "/template/admin/hu-HU/ui-elements/conversation-recepients-template.php", async: false});
CONTENT = twig({ ref: "conversation-recepients-template" }).render({D:data,UPLOAD_DIR:UPLOAD_DIR});
mfpResponse.data = generate_modal({TITLE:'Címzettek listája',CONTENT:CONTENT,CLASS:'',FOOTER:false})

}
}
});

  });

`

Generated content:
`

                                        <header class="panel-heading">
                                            <h2 class="panel-title">Címzettek listája</h2>
                                        </header>

                                        <div class="panel-body">
                                            <div class="modal-wrapper">

                                                <div class="modal-text">
                                                    <ul class="simple-user-list">


    <li class="col-md-6 row">
        <div class="col-md-10">
                                            <figure class="image rounded">
                                                <img src="/upload/1_avatar_12794700_1864564980436744_9151061640106972004_o.jpg" alt="Administrator" class="img-circle" style="width: 35px;">
                                            </figure>
                                            <a href="/users/1" class="title">Administrator</a>
                                            <span class="message truncate">pitt@jss.hu</span>
        </div>
        <div class="col-md-2">
            <button class="text-danger btn-xs" data-id="33" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
        </div>
    </li>

    <li class="col-md-6 row">
        <div class="col-md-10">
                                            <figure class="image rounded">
                                                <img src="/upload/default_profile_photo.png" alt="Test UserA" class="img-circle" style="width: 35px;">
                                            </figure>
                                            <a href="/users/2" class="title">Test UserA</a>
                                            <span class="message truncate">u1@user.hu</span>
        </div>
        <div class="col-md-2">
            <button class="text-danger btn-xs" data-id="34" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
        </div>
    </li>

    <li class="col-md-6 row">
        <div class="col-md-10">
                                            <figure class="image rounded">
                                                <img src="/upload/default_profile_photo.png" alt="Test UserB" class="img-circle" style="width: 35px;">
                                            </figure>
                                            <a href="/users/3" class="title">Test UserB</a>
                                            <span class="message truncate">u2@user.hu</span>
        </div>
        <div class="col-md-2">
            <button class="text-danger btn-xs" data-id="35" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>
        </div>
    </li>





                                    </section>`

**Comment by csimpi** [comment]
I tried both, but isnt works :( 
1.I put the js file after other script files.

2. 
After modal shows and gets console content, i use processNodes method, but isnt works (no errors in console).

**Comment by carsongross** [comment]
OK.  Can you try calling:

  Intercooler.processNodes($(‘.modal-basic’))

from the console, once the page has completely loaded and settled, to see if that makes things work?  That will tell us if intercooler is functioning properly, at least.

Are there other intercooler-powered items on the page that are working?

Cheers,
Carson

On April 4, 2016 at 1:37:28 PM, csimpi (notifications@github.com) wrote:

I tried both, but isnt works :(
1.I put the js file after other script files.

After modal shows and gets console content, i use processNodes method, but isnt works (no errors in console).

**Comment by carsongross** [comment]
Any update?

**Comment by csimpi** [comment]
Sorry, i will come back, i have to work a lot now :) but please keep open

**Comment by csimpi** [comment]
Intercooler.processNodes($(‘.panel-body’)) works instead of  Intercooler.processNodes($(‘.modal-basic’)) because the container of my button is .panel-body. 

.modal-basic class is the button what fires and generates the modal with the userlist and delete buttons.

**Comment by carsongross** [comment]
OK, so intercooler is working then.  The problem is almost certainly timing, where intercooler is processing the DOM before the javascript plugin rewrites the dom with the new HTML.

If you can find an event that fires after the plugin updates the dom, you can hook in an event handler to it and run Intercooler.processNodes() in that.

Cheers,
Carson

On April 7, 2016 at 10:22:42 AM, csimpi (notifications@github.com) wrote:

Intercooler.processNodes($(‘.panel-body’)) works instead of Intercooler.processNodes($(‘.modal-basic’)) because the container of my button is .panel-body.

.modal-basic class is the button what fires and generates the modal with the userlist and delete buttons.

**Comment by carsongross** [comment]
Closing this out due to lack of activity.

**Comment by csimpi** [comment]
Sorry for the inactivity i had to work a lot :)
My finally workaround is:

I had to use ajaxContentAdded callback function

`callbacks: {
  parseAjax: function(mfpResponse) {
    // mfpResponse.data is a "data" object from ajax "success" callback
    // for simple HTML file, it will be just String
    // You may modify it to change contents of the popup
    // For example, to show just #some-element:
    // mfpResponse.data = $(mfpResponse.data).find('#some-element');

    // mfpResponse.data must be a String or a DOM (jQuery) element

    console.log('Ajax content loaded:', mfpResponse);
  },
  ajaxContentAdded: function() {
    // Ajax content is loaded and appended to DOM
    Intercooler.processNodes($('.panel-body'));
    console.log(this.content);
  }
}
`

**Comment by carsongross** [comment]
Ah, looks like the additional content is being loaded via ajax.  That should work fine, glad you got it worked out!

Cheers,
Carson

On April 25, 2016 at 6:06:39 AM, csimpi (notifications@github.com) wrote:

Sorry for the inactivity i had to work a lot :)
My finally workaround is:

I had to use ajaxContentAdded callback function

`callbacks: {
parseAjax: function(mfpResponse) {
// mfpResponse.data is a "data" object from ajax "success" callback
// for simple HTML file, it will be just String
// You may modify it to change contents of the popup
// For example, to show just #some-element:
// mfpResponse.data = $(mfpResponse.data).find('#some-element');

// mfpResponse.data must be a String or a DOM (jQuery) element

console.log('Ajax content loaded:', mfpResponse);

},
ajaxContentAdded: function() {
// Ajax content is loaded and appended to DOM
Intercooler.processNodes($('.panel-body'));
console.log(this.content);
}
}
`
