### ISSUE TITLE
offline docs?

### ISSUE THREAD

**Issue by kmanley** [LeadDyno/intercooler-js#90]
I am planning to teach myself intercooler on a plane tomorrow, is it possible to generate offline docs? My naive attempt to cd www and python -m SimpleHTTPServer 8080 doesn't work too well.

**Comment by carsongross** [comment]
Hey Kevin,

The docs are build using Jekyll, a ruby library:

  http://jekyllrb.com/

Once you’ve installed jekyll, you can run

  jekyll serve

in the www directory, and the site should be available at

  http://localhost:4000

Hope you find the docs useful!

Cheers,
Carson

On April 12, 2016 at 6:07:55 PM, Kevin Manley (notifications@github.com) wrote:

I am planning to teach myself intercooler on a plane tomorrow, is it possible to generate offline docs? My naive attempt to cd www and python -m SimpleHTTPServer 8080 doesn't work too well.

**Comment by kmanley** [comment]
Thanks
