### ISSUE TITLE
DELETE method support

### ISSUE THREAD

**Issue by href** [LeadDyno/intercooler-js#91]
I've been using an older intercooler.js for a while now and I noticed that the latest version doesn't support PUT and DELETE requests anymore. Since I have an application that uses DELETE heavily I would have to either rewrite my views or add `_method` support to the framework I'm using.

Is there any way to go back to the old behaviour with the latest intercooler release? I only need to support modern browsers, so it's not a big deal for me that DELETE is not supported well.

Thanks for your help!

**Comment by carsongross** [comment]
Hi there.

Sorry for breaking that!  In the development branch I've added a meta-tag flag that allows you to enable the actual HTTP method:

`<meta name="intercoolerjs:use-actual-http-method" content="true"/>`

I'm going to cut another release on Friday if you can wait, or you can grab it out of the dev branch.

**Comment by href** [comment]
No worries. I read the changelog so you didn't *break* anything ;)
I can totally wait and I'm happy you re-enable the old ways with a setting.
