### ISSUE TITLE
beforeSend: passing custom arguments to data 

### ISSUE THREAD

**Issue by csimpi** [LeadDyno/intercooler-js#93]
I would like to passing all custom arguments which attribute starts with data-ic-*.
I try to use beforeSend, and modify data variable, but isnt works:

`<button class="text-danger btn-xs" data-ic-recipient-id="2" ic-delete-from="/api/messages/recipients" ic-src="/api/messages/recipients" ic-verb="DELETE" ic-trigger-on="default" ic-deps="ignore" ic-id="2"><i class="fa fa-trash"></i></button>`

```
            /** Intercooler can send data attributes datas automatically
             **/
            $(function(){
              $('body').on('beforeSend.ic', function(ev,elt,data){
                //$.blockUI();
                data['foo'] = 'bar';
                console.log("Intercooler beforeSend",data);
                //Console log says: Intercooler beforeSend ic-request=true&&ic-id=1&ic-current-url=%2Fadmin%2Fmessages%2F1&_method=DELETE
              }).on('complete.ic', function(){
                //$.unblockUI();
              });
            })
```

**Comment by carsongross** [comment]
Can you use the standard jQuery mechanism?

http://stackoverflow.com/questions/5618827/ajaxy-add-parameters-to-request

If not, could you use ic-global-include?

http://intercoolerjs.org/attributes/ic-global-include.html

If not, could you use cookies instead?  :)

**Comment by csimpi** [comment]
Not to pretty solutions.. :) Maybe i will try to change your script recognize attributes and automatically attatch data attributes as custom argument to the data.

Maybe can you give me some advice where can i found it these lines.

**Comment by csimpi** [comment]
/src/intercooler.js after line 531
` 
   $(elt).each(function() {
      $.each(this.attributes, function() {
        if(this.specified) {
          if (this.name.match(/^data-arg-(.*)/)) {
            console.log(this.name, this.value);
            data = appendData(data, this.name.replace(/^data-arg-/,''), this.value);
          }
        }
      });
    });
`

**Comment by carsongross** [comment]
Wait, could you use ic-include?  Sorry, would have mentioned it earlier, but I figured you had already seen it:

  http://intercoolerjs.org/attributes/ic-include.html



Cheers,
Carson

On April 25, 2016 at 2:44:52 PM, csimpi (notifications@github.com) wrote:

/src/intercooler.js after line 531

$(elt).each(function() {
$.each(this.attributes, function() {
if(this.specified) {
if (this.name.match(/^data-arg-(.*)/)) {
console.log(this.name, this.value);
data = appendData(data, this.name.replace(/^data-arg-/,''), this.value);
}
}
});
});

**Comment by csimpi** [comment]
I saw in doc, but i would not use different input elements, i would like pass custom variabless through ajax from the current element data-arg-* attributes.

Ex.:
I would like to delete one recipient from e-mail .conversation, i have to pass recipient id variable, and the conversation variable. 

<button class="text-danger btn-xs" data-arg-uid="102" data-arg-cid="12" ic-delete-from="/api/messages/recipients"><i class="fa fa-trash"></i></button>

**Comment by carsongross** [comment]
You can put arguments in as JSON with ic-include:

Syntax
The value of the ic-include attribute can either be a CSS/JQuery element selector of elements to include in the request or a JSON object of name/value pairs to include. If it is a JSON object, it must satisfy the jQuery parseJSON() requirements.


would that work?  

Cheers,
Carson

On April 25, 2016 at 2:57:31 PM, csimpi (notifications@github.com) wrote:

I saw in doc, but i would not use different input elements, i would like pass custom variabless through ajax from the current element data-arg-* attributes.

Ex.:
I would like to delete one recipient from e-mail .conversation, i have to pass recipient id variable, and the conversation variable.

**Comment by csimpi** [comment]
Yes i saw that too, and its really okay, but I usually use the data attributes for other things, and i would not like to add datas twice. I could use only from the JSON data, but use separeted data attributes more simple and as i know that's the usually way to pass  custom argument trough some javascript libs functions. (like nestable js plugin)

Thanks for your solutions! If you like my solution use it :)
