### ISSUE TITLE
X-IC-Script and 301

### ISSUE THREAD

**Issue by mayowa** [LeadDyno/intercooler-js#94]
Hi, Intercooler doesn't execute the X-IC-Script header directive if the server sends a redirect (301) in response to ic-post-from Is this deliberate?

**Comment by carsongross** [comment]
Unfortunately that's the nature of the ajax API: when a redirect occurs the original request headers are never passed down to the client in javascript.  Very annoying.  I've used a server-side session to pass headers across redirects to deal with it.

As a side note, it's also not possible to get the URL you were redirected to in any consistent manner, either.  There is an API for it, but IE, of course, doesn't implement it:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL

Very annoying.

**Comment by mayowa** [comment]
Ouch! Thanks for the quick response, and thank you very much for making and sharing Intercooler!
