### ISSUE TITLE
how to implement progress-bar by ic-post-to

### ISSUE THREAD

**Issue by tahmasebi** [LeadDyno/intercooler-js#96]
How can I implement a progress-bar instead spinner?

I can send percentage of progress to browser by `flush()`, but i don't know how to use it in Intercoolerjs.

Thank you.

**Comment by carsongross** [comment]
Hi Foad,

Sorry I didn’t respond to this earlier.  Right now there is not really any support for this in intercooler.  I have faked a progress bar before using events, but I haven’t published that code anywhere.

Cheers,
Carson

On May 21, 2016 at 2:44:48 AM, Foad Tahmasebi (notifications@github.com) wrote:

How can I implement a progress-bar instead spinner?

I can send percentage of progress to browser by flush(), but i don't know how to use it in Intercoolerjs.

Thank you.
