### ISSUE TITLE
change window title

### ISSUE THREAD

**Issue by tahmasebi** [LeadDyno/intercooler-js#97]
It's so better if I can change my browser window's `<title>` by something like this:

```
ic-title="title for new page" 
```
is it possible?

**Comment by carsongross** [comment]
That sounds like a good idea for a header to me.  How about you?

Cheers,
Carson

On May 24, 2016 at 6:41:14 AM, Foad Tahmasebi (notifications@github.com) wrote:

It's so better if I can change my browser window's <title> by something like this:

ic-title="title for new page"  

is it possible?

**Comment by tahmasebi** [comment]
I can't understand your mean clearly, but I think you don't agree whit this.

when I change my page content by intercoolerjs `ic-get-from` or `ic-post-to` and push url to browser by `ic-push-url` I expect browser's title  changes, but it doesn't change. 

I know it's not an ajax request but I think It's a nice format to change title in same time.

**Comment by carsongross** [comment]
What I mean is, if you could set an HTTP Response Header like ‘X-IC-Title: My new title’, then intercooler could update the title for you.

On the other hand, you can already use the X-IC-Script response header to do this:

  X-IC-Script: document.title = “My new title”

Hacky, but it would work. :)

Cheers,
Carson

On May 24, 2016 at 11:41:03 AM, Foad Tahmasebi (notifications@github.com) wrote:

@carsongross , I can't understand your mean clearly, but I think you don't agree with this.

when I change my page content by intercoolerjs ic-get-from or ic-post-to and push url to browser by ic-push-url I expect browser's title changes, but it doesn't change.

I know it's not an ajax request but I think It's a nice format to change title in same time.

Or if your mean is place this attribute in header section, I agree with your idea 👍

**Comment by n3storm** [comment]
Sorry, I don't understand how this issue ended up. Is this feature accepted or not?
Thanks in advance.

**Comment by tahmasebi** [comment]
@n3storm , yes it's accepted and now it's in branch `development`

**Comment by n3storm** [comment]
@tahmasebi great! thanks!

**Comment by carsongross** [comment]
Yep, I will be cutting  a new release with this in it later in June.
